(test "navigate a granted directory capability"
  (steps
    (expect-visible (role column :name "Folder browser"))
	(expect-visible (role panel :name "Directory controls"))
    (expect-visible (role checkbox :name "Show files as well as folders"))
    (focus (role button :name "Choose directory"))
    (press-key Enter)
    (expect-visible (text "Loading…"))
	(expect-visible (role panel :name "Loading status"))
	(click (role button :name "Choose directory"))
	(expect-visible (text "Loading…"))
    (focus (role checkbox :name "Show files as well as folders"))
    (press-key Space)
    (await-task)
    (expect-visible (role scroll :name "Directory contents"))
	(expect-visible (role panel :name "Directory view"))
    (expect-visible (role row :name "Directory breadcrumbs"))
    (expect-visible (role column :name "Directory entries"))
    (expect-visible (role button :name "Open directory nested"))
    (expect-not-visible (text "alpha.txt"))
    ; Names sort case-insensitively, so "nested" precedes "Uppercase-Folder".
    (expect-before (role row :name "Entry nested") (role row :name "Entry Uppercase-Folder"))
    (focus (role button :name "Open directory nested"))
    (press-key Enter)
    (await-task)
    (expect-visible (role button :name "Back"))
    ; The folder you are in is emphasised text, not another clickable chip.
    (expect-not-visible (role button :name "Breadcrumb 1"))
    (expect-visible (role button :name "Breadcrumb 0"))
    (click (role checkbox :name "Show files as well as folders"))
    (expect-visible (text "item.txt"))
    (expect-visible (text "0 folders · 1 file"))
    (focus (role button :name "Back"))
    (press-key Space)
    (await-task)
    (expect-visible (text "alpha.txt"))
    (click (role button :name "Open directory nested"))
    (await-task)
    (click (role button :name "Breadcrumb 0"))
    (await-task)
    (expect-visible (text "alpha.txt"))
    ; Folders sort ahead of files whatever order the listing arrived in.
    (expect-before (role row :name "Entry nested") (role row :name "Entry alpha.txt"))
    (expect-not-visible (role button :name "Back"))))
