(test "navigate a granted directory capability"
  (steps
    (expect-visible (role checkbox :name "Show files as well as folders"))
    (click (role button :name "Choose directory"))
    (expect-visible (text "Loading…"))
    (click (role checkbox :name "Show files as well as folders"))
    (await-task)
    (expect-visible (role scroll :name "Directory contents"))
    (expect-visible (role button :name "Open directory nested"))
    (expect-not-visible (text "File: alpha.txt"))
    (click (role button :name "Open directory nested"))
    (await-task)
    (expect-visible (role button :name "Back"))
    (expect-visible (role button :name "Breadcrumb 1"))
    (click (role checkbox :name "Show files as well as folders"))
    (expect-visible (text "File: item.txt"))
    (click (role button :name "Back"))
    (await-task)
    (expect-visible (text "File: alpha.txt"))
    (click (role button :name "Open directory nested"))
    (await-task)
    (click (role button :name "Breadcrumb 0"))
    (await-task)
    (expect-visible (text "File: alpha.txt"))
    (expect-not-visible (role button :name "Back"))))
