(test "navigate a granted directory capability"
  (steps
    (expect-visible (role column :name "Folder browser"))
	(expect-visible (role panel :name "Directory controls"))
    (expect-visible (role checkbox :name "Show files as well as folders"))
    (focus (role button :name "Choose directory"))
    (press-key Enter)
    (expect-visible (text "Loading…"))
	(expect-visible (role panel :name "Loading status"))
	(click (role button :name "Choose directory"))
	(expect-visible (text "Loading…"))
    (focus (role checkbox :name "Show files as well as folders"))
    (press-key Space)
    (await-task)
    (expect-visible (role scroll :name "Directory contents"))
	(expect-visible (role panel :name "Directory view"))
    (expect-visible (role row :name "Directory breadcrumbs"))
    (expect-visible (role column :name "Directory entries"))
    (expect-visible (role button :name "Open directory nested"))
    (expect-not-visible (text "File: alpha.txt"))
    (focus (role button :name "Open directory nested"))
    (press-key Enter)
    (await-task)
    (expect-visible (role button :name "Back"))
    (expect-visible (role button :name "Breadcrumb 1"))
    (click (role checkbox :name "Show files as well as folders"))
    (expect-visible (text "File: item.txt"))
    (focus (role button :name "Back"))
    (press-key Space)
    (await-task)
    (expect-visible (text "File: alpha.txt"))
    (click (role button :name "Open directory nested"))
    (await-task)
    (click (role button :name "Breadcrumb 0"))
    (await-task)
    (expect-visible (text "File: alpha.txt"))
    (expect-not-visible (role button :name "Back"))))
