; Photographs the list in a real window: one row treatment for every entry,
; names left-aligned at one x, folders first, long names truncated.
(test "Folder browser presents a scannable list"
  (grants
    (directory "fixture"))
  (steps
    (settle)
    (screenshot "initial")
    (click (role button :name "Choose directory"))
    (await-task)
    (settle)
    (expect-on-screen (role row :name "Directory breadcrumbs"))
    (expect-on-screen (role row :name "Entry alpha.txt"))
    (expect-on-screen (role button :name "Open directory nested"))
    (screenshot "listing")
    (screenshot "rows" :region (role scroll :name "Directory contents") :pad 8)
    (screenshot "long-name" :region (role row :name "Entry a-very-long-file-name-that-should-be-truncated-with-an-ellipsis-in-the-row.txt") :pad 8)
    (click (role button :name "Open directory many"))
    (await-task)
    (settle)
    (expect-on-screen (role button :name "Back"))
    (expect-on-screen (role button :name "Breadcrumb 0"))
    (screenshot "long-list")
    (screenshot "breadcrumbs" :region (role row :name "Directory breadcrumbs") :pad 8)
    (click (role button :name "Open directory zzz-folder"))
    (await-task)
    (settle)
    (screenshot "deep")
    (click (role checkbox :name "Show files as well as folders"))
    (settle)
    (expect-visible (text "No folders here"))
    (screenshot "no-folders")))
