;; The scaling case for capture tabs: 50 captures open at once, one tab
;; each, opened through the folder list as a person would. Switching from
;; the last tab back to the first mounts that capture's view from what its
;; tab held and reads nothing; its work does not grow with the tabs open.
(test "switch among 50 open captures"
  (grants
    (directory "fixture/scale-100"))
  (benchmark :warmups 1 :samples 3 :iterations 1 :scale 50 :initial-size 50 :change-size 1)
  (steps
    (click (role button :name "Open folder"))
    (await-task)
    (click (role button :name "Capture run-0000.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0001.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0002.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0003.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0004.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0005.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0006.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0007.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0008.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0009.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0010.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0011.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0012.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0013.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0014.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0015.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0016.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0017.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0018.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0019.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0020.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0021.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0022.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0023.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0024.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0025.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0026.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0027.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0028.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0029.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0030.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0031.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0032.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0033.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0034.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0035.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0036.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0037.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0038.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0039.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0040.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0041.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0042.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0043.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0044.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0045.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0046.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0047.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0048.rgstats"))
    (await-task)
    (click (role button :name "Open another capture"))
    (click (role button :name "Capture run-0049.rgstats"))
    (await-task)
    (expect-selected (role tab :name "run-0049.rgstats"))
    ; every tab offers its close button
    (expect-count (button-prefix "Close run-") 50)
    (mark-metrics)
    (click (role tab :name "run-0000.rgstats"))
    (expect-selected (role tab :name "run-0000.rgstats"))
    ; the window, the tabs, the capture, trust, and baseline bars, the
    ; Overview, and the inspector render for the arriving capture; the
    ; view rail is kept. None of it depends on how many tabs are open
    (expect-component-work :rendered 7 :compared 7 :skipped 1 :mounted 0 :retired 0)))
