;; Drives the real window through the capture list and each view of one
;; capture, photographing each so the layout can be reviewed against the
;; wireframes.
(test "the window presents the capture list and every view of a capture"
  (grants
    (directory "fixture/captures"))
  (steps
    (settle)
    (expect-on-screen (role row :name "Observatory header"))
    (expect-on-screen (role row :name "Authority bar"))
    (screenshot "start")
    (click (role button :name "Open folder"))
    (await-task)
    (settle)
    (expect-on-screen (role virtual-list :name "Captures"))
    (screenshot "captures")
    (click (role button :name "Capture database-browser-scale-100.rgstats"))
    (await-task)
    (settle)
    (expect-on-screen (role row :name "Capture bar"))
    (screenshot "overview")
    (click (role button :name "Interactions"))
    (settle)
    (screenshot "interactions")
    (click (role button :name "Cycle r4 #7"))
    (await-task)
    (settle)
    (expect-on-screen (role virtual-list :name "Cycles"))
    (screenshot "inspector")
    (scroll (role scroll :name "Interactions scroll") :to (role row :name "Sum check"))
    (settle)
    (expect-on-screen (role row :name "Sum check"))
    (screenshot "waterfall")
    (scroll (role scroll :name "Interactions scroll") :to (role row :name "Allocation platform_lowering"))
    (settle)
    (expect-on-screen (role row :name "Allocation platform_lowering"))
    (screenshot "cycle-work")
    (scroll (role scroll :name "Interactions scroll") :to (role button :name "Show step"))
    (settle)
    (click (role button :name "Show step"))
    (await-task)
    (settle)
    (expect-on-screen (role panel :name "Focused step"))
    (screenshot "spec")
    (click (role button :name "Memory"))
    (settle)
    (screenshot "memory")
    (click (role button :name "Health"))
    (settle)
    (screenshot "health")
    (click (role button :name "Back to captures"))
    (settle)
    (click (role button :name "Capture interrupted.rgstats"))
    (await-task)
    (settle)
    (expect-on-screen (role panel :name "Untrusted capture"))
    (screenshot "untrusted")
    (click (role button :name "Back to captures"))
    (settle)
    (click (role button :name "Capture schema-4.rgstats"))
    (await-task)
    (settle)
    (expect-on-screen (role panel :name "Capture error"))
    (screenshot "refused")))
