;; Drives the real window through a comparison and a scaling set, and
;; photographs each so the layout can be reviewed against W7 and W8: the
;; comparability sheet of an A/A pair and of an incomparable pair, the
;; triggers table with its Δ columns, and the scaling gate, ratios, and chart.
(test "the window presents comparison and scaling"
  (grants
    (directory "fixture/compare"))
  (steps
    (click (role button :name "Open folder"))
    (await-task)
    (click (role button :name "Capture browse-100.rgstats"))
    (await-task)
    (click (role button :name "Set as baseline"))
    (click (role button :name "Back to captures"))
    (click (role button :name "Capture browse-100-b.rgstats"))
    (await-task)
    (click (role button :name "Compare"))
    (settle)
    (scroll (role scroll :name "Compare scroll") :to (role button :name "Use browse-100-aa.rgstats as A/A"))
    (settle)
    (click (role button :name "Use browse-100-aa.rgstats as A/A"))
    (await-task)
    (settle)
    (expect-on-screen (role row :name "A/A verdict"))
    (screenshot "noise")
    (scroll (role scroll :name "Compare scroll") :to (role row :name "Gate schema_version"))
    (settle)
    (expect-on-screen (role row :name "Gate schema_version"))
    (screenshot "compare")
    (click (role button :name "Interactions"))
    (settle)
    (expect-on-screen (role button :name "Sort triggers by delta"))
    (screenshot "deltas")
    (click (role button :name "Back to captures"))
    (click (role button :name "Capture browse-100-jobs-2.rgstats"))
    (await-task)
    (click (role button :name "Compare"))
    (settle)
    (expect-on-screen (role row :name "Gate timing_quality"))
    (screenshot "incomparable")
    (click (role button :name "Scaling"))
    (click (role button :name "Scaling set browse-100.rgstats"))
    (click (role button :name "Scaling set browse-1k.rgstats"))
    (click (role button :name "Scaling set browse-10k.rgstats"))
    (click (role button :name "Build scaling set"))
    (await-task)
    (settle)
    (screenshot "scaling")
    (scroll (role scroll :name "Scaling scroll") :to (role column :name "Scaling ratios"))
    (settle)
    (expect-on-screen (role column :name "Scaling ratios"))
    (screenshot "ratios")
    (scroll (role scroll :name "Scaling scroll") :to (role canvas-item :name "Point task callback 10000"))
    (settle)
    (expect-on-screen (role canvas-item :name "Point task callback 10000"))
    (screenshot "chart")))
