;; The real window in both schemes: the capture list, a capture's overview,
;; its cycles with their targets, and the Timeline, photographed light and
;; then dark, so both palettes can be reviewed against each other.
(test "the window presents its key views in both themes"
  (grants
    (directory "fixture/window")
    (theme light))
  (steps
    (settle)
    (click (role button :name "Open folder"))
    (await-task)
    (settle)
    (screenshot "light-captures")
    (click (role button :name "Capture database-browser-rows.rgstats"))
    (await-task)
    (settle)
    (screenshot "light-overview")
    (click (role button :name "Interactions"))
    (settle)
    (screenshot "light-interactions")
    (click (role button :name "Timeline"))
    (await-task)
    (settle)
    (pointer-move (role canvas :name "Timeline") 203 50)
    (settle)
    (screenshot "light-timeline")
    (system-theme dark)
    (settle)
    (expect-theme dark)
    (screenshot "dark-timeline")
    (click (role button :name "Interactions"))
    (settle)
    (screenshot "dark-interactions")
    (click (role button :name "Overview"))
    (settle)
    (screenshot "dark-overview")
    (click (role button :name "Back to captures"))
    (settle)
    (screenshot "dark-captures")))
