(test "Reopening retains draft state but replaces the board definition and its owned item"
  (steps
    (click (role button :name "Edit draft"))
    (expect-visible (text "Draft 1"))
    (click (role button :name "Refresh queue"))
    (expect-component-work :rendered 2 :compared 1 :skipped 1 :mounted 0 :retired 0)
    (click (role button :name "Refresh queue"))
    (expect-component-work :rendered 1 :compared 1 :skipped 1 :mounted 0 :retired 0)
    (click (role button :name "Reopen board"))
    (expect-visible (text "Draft 1"))
    (expect-component-work :rendered 3 :compared 0 :skipped 0 :mounted 2 :retired 2)
    (click (role button :name "Edit draft"))
    (expect-visible (text "Draft 2"))
    (click (role button :name "Refresh queue"))
    (expect-component-work :rendered 2 :compared 1 :skipped 1 :mounted 0 :retired 0)
    (click (role button :name "Refresh queue"))
    (expect-component-work :rendered 1 :compared 1 :skipped 1 :mounted 0 :retired 0)
    (click (role button :name "Reopen board"))
    (expect-visible (text "Draft 2"))
    (expect-component-work :rendered 3 :compared 0 :skipped 0 :mounted 2 :retired 2)))
