(test "Draft ownership, delegation and memoized ancestor invalidation"
  (steps
    (expect-visible (text "Draft 0"))
    (click (role button :name "Refresh queue"))
    (expect-component-work :rendered 1 :compared 1 :skipped 1 :mounted 0 :retired 0)
    (click (role button :name "Edit draft"))
    (expect-visible (text "Draft 1"))
    (expect-visible (text "Accepted 0"))
    (expect-component-work :rendered 1 :compared 1 :skipped 0 :mounted 0 :retired 0 :ancestor-invalidations 2)
    (click (role button :name "Reset draft"))
    (expect-visible (text "Draft 0"))
    (expect-not-visible (text "Draft 1"))
    (click (role button :name "Double step"))
    (click (role button :name "Edit draft"))
    (expect-visible (text "Draft 2"))
    (click (role button :name "Accept draft"))
    (expect-visible (text "Accepted 2"))
    (click (role button :name "Edit draft"))
    (expect-visible (text "Draft 4"))
    (click (role button :name "Accept draft"))
    (expect-visible (text "Accepted 2"))
    (expect-component-work :rendered 0 :compared 0 :skipped 0)
    (click (role button :name "Toggle board"))
    (expect-visible (text "No board"))
    (expect-component-work :rendered 1 :mounted 0 :retired 2)
    (click (role button :name "Toggle board"))
    (expect-visible (text "Draft 4"))
    (expect-component-work :rendered 3 :mounted 2 :retired 0)))
