(test "the empty state offers one action and is returned to intact"
  (grants
    (directory "fixture"))
  (steps
    (expect-visible (text "Open a project to begin"))
    (expect-not-visible (role button :name "Back"))
    (expect-not-visible (role button :name "Forward"))
    (expect-not-visible (role button :name "Close directory"))
    (expect-not-visible (role virtual-list :name "Directory entries"))
    (expect-not-visible (role panel :name "Selection details"))
    (click (role button :name "Open project"))
    (await-task)
    (expect-visible (role virtual-list :name "Directory entries"))
    (click (role button :name "Select File: alpha.txt"))
    (expect-visible (role panel :name "Selection details"))
    (click (role button :name "Close directory"))
    (click (role button :name "Confirm close directory"))
    (expect-visible (text "Open a project to begin"))
    (expect-not-visible (role panel :name "Selection details"))
    (expect-not-visible (role button :name "Close directory"))
    (expect-not-visible (role virtual-list :name "Directory entries"))
    (click (role button :name "Open project"))
    (await-task)
    (expect-visible (role virtual-list :name "Directory entries"))
    (expect-visible (text "fixture"))
    (expect-file-picks 2)))
