(test "history presses at their boundaries change nothing"
  (steps
    (click (role button :name "Open project"))
    (await-task)
    (expect-visible (text "fixture"))
    (click (role button :name "Breadcrumb root"))
    (expect-patch :kind no_change :staged 0 :removed 0)
    (expect-visible (text "fixture"))
    (click (role button :name "Open folder nested"))
    (await-task)
    (expect-visible (text "fixture / nested"))
    (click (role button :name "Select File: item.txt"))
    (expect-visible (text "Selected: item.txt"))
    (click (role button :name "Back"))
    (expect-not-visible (role panel :name "Selection details"))
    (expect-visible (text "fixture"))
    (click (role button :name "Forward"))
    (expect-visible (text "fixture / nested"))
    (expect-file-opens 1)))
