(test "navigate nested folders, select entries, and preserve history"
  (steps
    (expect-file-picks 0) (expect-file-lists 0) (expect-file-opens 0) (expect-file-reads 0)
    (click (role button :name "Open project"))
    (await-task)
    (expect-file-picks 1) (expect-file-lists 1) (expect-file-opens 0) (expect-file-reads 0)
    (click (role button :name "Select Folder: nested"))
    (expect-visible (text "Selected: nested"))
    (click (role button :name "Open folder nested"))
    (await-task)
    (expect-visible (text "fixture / nested"))
    (expect-file-picks 1) (expect-file-lists 2) (expect-file-opens 1) (expect-file-reads 0)
    (click (role button :name "Select File: item.txt"))
    (expect-visible (text "Selected: item.txt"))
    (click (role button :name "Back"))
    (expect-visible (role button :name "Open folder nested"))
    (click (role button :name "Forward"))
    (expect-visible (text "fixture / nested"))
    (click (role button :name "Breadcrumb root"))
    (expect-visible (role button :name "Open folder nested"))
    (expect-file-picks 1) (expect-file-lists 2) (expect-file-opens 1) (expect-file-reads 0)))
