(test "the catalogue and every panel are on screen at the default window size"
  (steps
    (settle)
    (expect-on-screen (role panel :name "Settings catalogue"))
    (expect-on-screen (role panel :name "Profile settings"))
    (expect-on-screen (role panel :name "Managed setting"))
    (expect-on-screen (role virtual-list :name "Matching settings"))
    (expect-on-screen (text "Notifications — Task completion"))
    (expect-on-screen (role textbox :name "Profile name"))
    (expect-on-screen (role button :name "Apply profile"))
    (expect-bounds (role virtual-list :name "Matching settings") :min-height 300)
    (expect-bounds (role button :name "Open rename dialog") :max-height 44 :max-width 160)
    (expect-bounds (role column :name "Status") :min-height 50 :max-height 66)
    (screenshot "catalogue")
    (click (role button :name "Category Privacy"))
    (settle)
    (expect-on-screen (text "3 settings match “Privacy”"))
    (expect-on-screen (text "Privacy — Crash reports"))
    (expect-bounds (role column :name "Status") :min-height 50 :max-height 66)
    (screenshot "privacy-selected" :region (role panel :name "Settings catalogue") :pad 8)))
