(test "a rejected request is followed by a working one and back again"
  (grants
    (http-origin "http://127.0.0.1:38191")
    (server "fixture_server.py" 38191))
  (steps
    (replace-text (role textbox :name "Request URL") "file:///etc/passwd")
    (click (role button :name "Send request"))
    (await-task)
    (expect-visible (text "Only HTTP and HTTPS URLs are supported"))
    (replace-text (role textbox :name "Request URL") "http://127.0.0.1:38191/echo")
    (replace-text (role textarea :name "Request body") "recovered")
    (click (role button :name "Send request"))
    (await-task)
    (expect-not-visible (role panel :name "Request error"))
    (expect-visible (text "Status 200"))
    (expect-value (role textarea :name "Response body") "recovered")
    (replace-text (role textbox :name "Request URL") "file:///etc/passwd")
    (click (role button :name "Send request"))
    (await-task)
    (expect-visible (role panel :name "Request error"))
    (expect-value (role textarea :name "Response body") "")
    (expect-http-counters 0 3 3 0)))
