(test "discover connect and apply a device profile"
  (grants
    (device virtual))
  (steps
    (expect-visible (role column :name "Device Configurator"))
    (expect-device-connections 0)
    (click (role button :name "Discover devices"))
    (await-task)
    (expect-visible (text "Found 1 device"))
    (expect-visible (text "Device 0: Roc Labs Aurora Control Pad"))
    (click (role button :name "Connect device"))
    (await-task)
    (expect-device-connections 1)
    (expect-device-transactions 1)
    (expect-visible (text "Connected and synchronized"))
    (expect-visible (text "Sensitivity: 800 DPI"))
    (click (role button :name "Increase sensitivity"))
    (expect-visible (text "Sensitivity: 900 DPI"))
    (click (role checkbox :name "Device lighting"))
    (click (role button :name "Select profile 3"))
    (click (role button :name "Apply configuration"))
    (await-task)
    (expect-device-transactions 2)
    (expect-visible (text "Configuration applied"))
	(click (role button :name "Disconnect device"))
	(await-task)
	(expect-visible (text "Disconnected"))
	(expect-device-connections 0)))
