(test "discover connect and apply a device profile"
  (grants
    (device virtual))
  (steps
    (expect-visible (role column :name "Device Configurator"))
    (expect-device-connections 0)
    (click (role button :name "Discover devices"))
    (await-task)
    (expect-visible (text "Found 1 device"))
    (expect-visible (text "Device 0: Roc Labs Aurora Control Pad"))
    (click (role button :name "Connect device"))
    (await-task)
    (expect-device-connections 1)
    (expect-device-transactions 1)
    (expect-visible (text "Connected and synchronized"))
    (expect-visible (text "800"))
    (expect-visible (text "DPI"))
    (expect-visible (text "100 – 3200 DPI in steps of 100"))
    (click (role button :name "Increase sensitivity"))
    (expect-visible (text "900"))
    ; The edit is held here and said to be held here.
    (expect-visible (text "Held here, not on the device"))
    (click (role checkbox :name "Device lighting"))
    (click (role button :name "Select profile 3"))
    (click (role button :name "Apply configuration"))
    (await-task)
    (expect-device-transactions 2)
    (expect-visible (text "Configuration applied"))
    (expect-visible (text "The device has everything shown here"))
    ; Profile 3 is the one in force, and the panel says so in words as well as
    ; in the lit control.
    (expect-visible (text "PROFILE 3 OF 5"))
	(click (role button :name "Disconnect device"))
	(await-task)
	(expect-visible (text "Disconnected"))
	(expect-device-connections 0)))
