; The upper bound, pressed past its end. Sensitivity stops at the highest value
; the device accepts instead of climbing through it, and the applied transaction
; carries that bounded value.
(test "sensitivity stops at its ceiling"
  (grants
    (device virtual))
  (steps
    (click (role button :name "Discover devices"))
    (await-task)
    (click (role button :name "Connect device"))
    (await-task)
    (expect-visible (text "Sensitivity: 800 DPI"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (click (role button :name "Increase sensitivity"))
    (expect-visible (text "Sensitivity: 3200 DPI"))
    (click (role button :name "Apply configuration"))
    (await-task)
    (expect-visible (text "Configuration applied"))
    (expect-visible (text "Sensitivity: 3200 DPI"))
    (expect-device-transactions 2)
    ; One step down from the ceiling is an ordinary step, not another clamp.
    (click (role button :name "Decrease sensitivity"))
    (expect-visible (text "Sensitivity: 3100 DPI"))))
