(test "configuration remains bounded before apply"
  (grants
    (device virtual))
  (steps
    (click (role button :name "Discover devices"))
    (await-task)
    (click (role button :name "Connect device"))
    (await-task)
    (click (role button :name "Decrease sensitivity"))
    (click (role button :name "Decrease sensitivity"))
    (click (role button :name "Decrease sensitivity"))
    (click (role button :name "Decrease sensitivity"))
    (click (role button :name "Decrease sensitivity"))
    (click (role button :name "Decrease sensitivity"))
    (click (role button :name "Decrease sensitivity"))
    (click (role button :name "Decrease sensitivity"))
    (expect-visible (text "100"))
    (click (role button :name "Apply configuration"))
    (await-task)
    (expect-visible (text "Configuration applied"))))
