//! Roc Platform ABI
//!
//! This file defines the Rust interface for hosted functions in a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must release owned refcounted arguments when done, using
//!   the release call named in each hosted symbol's doc comment below.
//! - Releasing a container releases its elements only when the container's own
//!   count reaches zero, which is what compiled Roc code does when it drops one
//!   it owns. Releasing the elements unconditionally double-frees them whenever
//!   the Roc caller still holds the container.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Import this module from the platform host and implement the listed hosted symbols
//! with the exact natural C ABI signatures shown below.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(dead_code)]
#![allow(improper_ctypes)]
#![allow(improper_ctypes_definitions)]
// `no_roc_std_helpers` is supplied by host build tooling and cannot be registered from source.
#![allow(unexpected_cfgs)]

use core::ffi::c_void;
use core::sync::atomic::{fence, AtomicIsize, Ordering};
#[cfg(not(no_roc_std_helpers))]
use std::alloc::Layout;

/// Runtime representation of Roc's fixed-point `Dec` value.
///
/// `num` stores the decimal value scaled by 10^18.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RocDec {
    pub num: i128,
}

const _: [(); 16] = [(); core::mem::size_of::<RocDec>()];
const _: [(); 16] = [(); core::mem::align_of::<RocDec>()];

#[cfg(target_arch = "x86_64")]
type RocU8x16Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "x86_64")]
type RocI8x16Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "x86_64")]
type RocU16x8Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "x86_64")]
type RocI16x8Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "x86_64")]
type RocU32x4Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "x86_64")]
type RocI32x4Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "x86_64")]
type RocU64x2Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "x86_64")]
type RocI64x2Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "aarch64")]
type RocU8x16Native = core::arch::aarch64::uint8x16_t;
#[cfg(target_arch = "aarch64")]
type RocI8x16Native = core::arch::aarch64::int8x16_t;
#[cfg(target_arch = "aarch64")]
type RocU16x8Native = core::arch::aarch64::uint16x8_t;
#[cfg(target_arch = "aarch64")]
type RocI16x8Native = core::arch::aarch64::int16x8_t;
#[cfg(target_arch = "aarch64")]
type RocU32x4Native = core::arch::aarch64::uint32x4_t;
#[cfg(target_arch = "aarch64")]
type RocI32x4Native = core::arch::aarch64::int32x4_t;
#[cfg(target_arch = "aarch64")]
type RocU64x2Native = core::arch::aarch64::uint64x2_t;
#[cfg(target_arch = "aarch64")]
type RocI64x2Native = core::arch::aarch64::int64x2_t;
#[cfg(target_arch = "wasm32")]
type RocU8x16Native = core::arch::wasm32::v128;
#[cfg(target_arch = "wasm32")]
type RocI8x16Native = core::arch::wasm32::v128;
#[cfg(target_arch = "wasm32")]
type RocU16x8Native = core::arch::wasm32::v128;
#[cfg(target_arch = "wasm32")]
type RocI16x8Native = core::arch::wasm32::v128;
#[cfg(target_arch = "wasm32")]
type RocU32x4Native = core::arch::wasm32::v128;
#[cfg(target_arch = "wasm32")]
type RocI32x4Native = core::arch::wasm32::v128;
#[cfg(target_arch = "wasm32")]
type RocU64x2Native = core::arch::wasm32::v128;
#[cfg(target_arch = "wasm32")]
type RocI64x2Native = core::arch::wasm32::v128;

macro_rules! roc_simd_type {
    ($name:ident, $native:ident) => {
        #[repr(transparent)]
        #[derive(Clone, Copy)]
        pub struct $name(pub $native);
        const _: [(); 16] = [(); core::mem::size_of::<$name>()];
        const _: [(); 16] = [(); core::mem::align_of::<$name>()];
    };
}
roc_simd_type!(RocU8x16, RocU8x16Native);
roc_simd_type!(RocI8x16, RocI8x16Native);
roc_simd_type!(RocU16x8, RocU16x8Native);
roc_simd_type!(RocI16x8, RocI16x8Native);
roc_simd_type!(RocU32x4, RocU32x4Native);
roc_simd_type!(RocI32x4, RocI32x4Native);
roc_simd_type!(RocU64x2, RocU64x2Native);
roc_simd_type!(RocI64x2, RocI64x2Native);


/// Runtime representation of an opaque `Box(T)` value.
pub type RocBox = *mut c_void;

/// Host-internal allocator and diagnostic context used by helper functions in this file.
///
/// Compiled Roc code does not receive this value. The real host ABI is the set of direct
/// linker symbols declared below (`roc_alloc`, hosted symbols, and provided entrypoints).
#[repr(C)]
pub struct RocHost {
    pub env: *mut c_void,
    pub roc_alloc: extern "C" fn(*mut RocHost, usize, usize) -> *mut c_void,
    pub roc_dealloc: extern "C" fn(*mut RocHost, *mut c_void, usize),
    pub roc_realloc: extern "C" fn(*mut RocHost, *mut c_void, usize, usize) -> *mut c_void,
    pub roc_dbg: extern "C" fn(*mut RocHost, *const u8, usize),
    pub roc_expect_failed: extern "C" fn(*mut RocHost, *const u8, usize),
    pub roc_crashed: extern "C" fn(*mut RocHost, *const u8, usize),
}

impl RocHost {
    /// Allocate memory with the given alignment and length.
    ///
    /// # Safety
    /// The returned pointer must be used only according to Roc allocation layout
    /// rules and later released through the matching host deallocator.
    #[inline]
    pub unsafe fn alloc(&self, alignment: usize, length: usize) -> *mut c_void {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_alloc)(host, length, alignment)
    }

    /// Deallocate memory previously allocated with `alloc`.
    ///
    /// # Safety
    /// `ptr` must have been allocated by this host with the same alignment and must
    /// not be used after this call.
    #[inline]
    pub unsafe fn dealloc(&self, ptr: *mut c_void, alignment: usize) {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_dealloc)(host, ptr, alignment);
    }

    /// Reallocate memory to a new size.
    ///
    /// # Safety
    /// `old_ptr` must have been allocated by this host with the same alignment.
    /// The returned pointer replaces `old_ptr`; the old pointer must not be used.
    #[inline]
    pub unsafe fn realloc(
        &self,
        old_ptr: *mut c_void,
        alignment: usize,
        new_length: usize,
    ) -> *mut c_void {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_realloc)(host, old_ptr, new_length, alignment)
    }
}

#[inline]
fn checked_add_usize(left: usize, right: usize, context: &str) -> usize {
    left.checked_add(right).expect(context)
}

#[inline]
fn checked_mul_usize(left: usize, right: usize, context: &str) -> usize {
    left.checked_mul(right).expect(context)
}

#[inline]
fn shifted_capacity(capacity: usize) -> usize {
    capacity.checked_shl(1).expect("Roc capacity does not fit shifted representation")
}

/// Uniform ABI function pointer stored in `RocErasedCallablePayload`.
///
/// The final `reuse` pointer is nullable. Non-null must be the callable data
/// pointer whose inline capture begins at `capture`; it transfers one owned
/// reference to the callee. The caller must not use or decref that ownership
/// unit after the call. The callee consumes it exactly once, whether or not the
/// result can reuse the allocation.
pub type RocErasedCallableFn = extern "C" fn(*mut RocHost, *mut u8, *const u8, *mut u8, *mut u8, *mut *const c_void);

/// Final-drop callback for inline erased-callable captures.
pub type RocErasedCallableOnDrop = extern "C" fn(*mut u8, *mut RocHost);

/// Payload header for `Box(function)`.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct RocErasedCallablePayload {
    pub callable_fn_ptr: RocErasedCallableFn,
    pub on_drop: Option<RocErasedCallableOnDrop>,
}

const _: () = assert!(core::mem::size_of::<RocErasedCallablePayload>() == 2 * core::mem::size_of::<usize>(), "RocErasedCallablePayload size mismatch");
const _: () = assert!(core::mem::offset_of!(RocErasedCallablePayload, callable_fn_ptr) == 0, "RocErasedCallablePayload.callable_fn_ptr offset mismatch");
const _: () = assert!(core::mem::offset_of!(RocErasedCallablePayload, on_drop) == core::mem::size_of::<usize>(), "RocErasedCallablePayload.on_drop offset mismatch");

/// Runtime representation of `Box(function)`.
pub type RocErasedCallable = *mut u8;

pub const ROC_ERASED_CALLABLE_CAPTURE_ALIGNMENT: usize = 16;
pub const ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT: usize = 16;
pub const ROC_ERASED_CALLABLE_CAPTURE_OFFSET: usize =
    (core::mem::size_of::<RocErasedCallablePayload>() + 15) & !15;

#[inline]
pub fn roc_erased_callable_payload_size(capture_size: usize) -> usize {
    checked_add_usize(
        ROC_ERASED_CALLABLE_CAPTURE_OFFSET,
        capture_size,
        "Roc erased-callable payload size overflow",
    )
}

#[inline]
/// # Safety
/// `callable` must be a non-null Roc erased-callable data pointer.
pub unsafe fn roc_erased_callable_payload_ptr(callable: RocErasedCallable) -> *mut RocErasedCallablePayload {
    callable as *mut RocErasedCallablePayload
}

#[inline]
/// # Safety
/// `callable` must be a non-null Roc erased-callable data pointer.
pub unsafe fn roc_erased_callable_capture_ptr(callable: RocErasedCallable) -> *mut u8 {
    callable.add(ROC_ERASED_CALLABLE_CAPTURE_OFFSET)
}

/// Allocate a Roc erased callable payload.
///
/// # Safety
/// The caller must initialize and use the returned callable according to Roc's
/// erased-callable ABI. `callable_fn_ptr` and `on_drop` must have matching ABI
/// signatures for the captured payload.
pub unsafe fn roc_erased_callable_allocate(
    roc_host: &RocHost,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: Option<RocErasedCallableOnDrop>,
    capture_size: usize,
) -> RocErasedCallable {
    let ptr_width = core::mem::size_of::<usize>();
    let alignment = core::cmp::max(ptr_width, ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT);
    let extra_bytes = core::cmp::max(ptr_width, ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT);
    let total = checked_add_usize(
        extra_bytes,
        roc_erased_callable_payload_size(capture_size),
        "Roc erased-callable allocation size overflow",
    );
    let base = roc_host.alloc(alignment, total) as *mut u8;
    let data = base.add(extra_bytes);
    let rc = data.sub(core::mem::size_of::<isize>()) as *mut isize;
    *rc = 1;
    let payload = roc_erased_callable_payload_ptr(data);
    *payload = RocErasedCallablePayload { callable_fn_ptr, on_drop };
    data
}

/// Payload drop callback for a boxed value.
///
/// The callback receives the boxed payload data pointer and must recursively
/// decref any Roc refcounted values inside the payload. It must not free the
/// box allocation; `decref_box_with` and `free_box_with` free it after the callback.
pub type RocBoxPayloadDecref = extern "C" fn(*mut c_void, *mut RocHost);

/// Increment the refcount of a boxed payload data pointer.
///
/// # Safety
/// `data_ptr` must be a valid Roc box payload pointer. The caller must ensure
/// that the extra retained references are balanced by later decrefs.
pub unsafe fn incref_box(data_ptr: RocBox, amount: isize) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    let rc = box_refcount_ptr(data);
    if unsafe { (*rc).load(Ordering::Relaxed) } == 0 {
        return; // REFCOUNT_STATIC_DATA
    }
    unsafe {
        (*rc).fetch_add(amount, Ordering::Relaxed);
    }
}

/// Allocate a Roc box and return a pointer to its payload data.
///
/// # Safety
/// The returned payload memory is uninitialized. The caller must initialize it
/// according to the Roc type before exposing it to safe APIs or Roc code.
pub unsafe fn allocate_box(
    payload_size: usize,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: &RocHost,
) -> RocBox {
    let ptr_width = core::mem::size_of::<usize>();
    let required_space = if payload_contains_refcounted { checked_mul_usize(2, ptr_width, "Roc box header size overflow") } else { ptr_width };
    let header_bytes = required_space.max(payload_alignment);
    let alloc_alignment = ptr_width.max(payload_alignment);
    let total = checked_add_usize(header_bytes, payload_size, "Roc box allocation size overflow");
    let base = roc_host.alloc(alloc_alignment, total) as *mut u8;
    let data = base.add(header_bytes);
    unsafe {
        let rc = data.sub(core::mem::size_of::<isize>()) as *mut isize;
        *rc = 1;
    }
    data as RocBox
}

/// Decrement a pointer-aligned boxed payload with no Roc refcounted values.
///
/// # Safety
/// `data_ptr` must be a valid Roc box payload pointer owned by this reference.
pub unsafe fn decref_box(data_ptr: RocBox, roc_host: &RocHost) {
    unsafe {
        decref_box_with(data_ptr, core::mem::align_of::<usize>(), false, None, roc_host);
    }
}

/// Increment a boxed function closure.
///
/// # Safety
/// `callable` must be a valid Roc erased-callable payload pointer.
pub unsafe fn incref_erased_callable(callable: RocErasedCallable, amount: isize) {
    unsafe {
        incref_box(callable as RocBox, amount);
    }
}

/// Decrement a boxed function closure and run its capture drop callback on final release.
///
/// # Safety
/// `callable` must be a valid Roc erased-callable payload pointer owned by this reference.
pub unsafe fn decref_erased_callable(callable: RocErasedCallable, roc_host: &RocHost) {
    unsafe {
        decref_box_with(
            callable as RocBox,
            ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT,
            false,
            Some(drop_erased_callable_payload),
            roc_host,
        );
    }
}

extern "C" fn drop_erased_callable_payload(data_ptr: *mut c_void, roc_host: *mut RocHost) {
    if data_ptr.is_null() || roc_host.is_null() {
        return;
    }
    unsafe {
        let callable = data_ptr as RocErasedCallable;
        let payload = roc_erased_callable_payload_ptr(callable);
        if let Some(on_drop) = (*payload).on_drop {
            on_drop(roc_erased_callable_capture_ptr(callable), roc_host);
        }
    }
}

/// Decrement a boxed payload and run payload teardown when this is the final ref.
///
/// `payload_contains_refcounted` must match the value passed to `allocate_box`:
/// it determines the box header size, and is independent of whether a
/// `payload_decref` teardown callback is supplied. A host resource handle such
/// as `Box(U64)` holding a raw pointer has `payload_contains_refcounted: false`
/// even when it provides a teardown callback to free the underlying resource.
///
/// # Safety
/// `data_ptr` must be a valid Roc box payload pointer owned by this reference,
/// and `payload_alignment`/`payload_contains_refcounted` must match allocation.
pub unsafe fn decref_box_with(
    data_ptr: RocBox,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    payload_decref: Option<RocBoxPayloadDecref>,
    roc_host: &RocHost,
) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    let rc = box_refcount_ptr(data);
    if unsafe { (*rc).load(Ordering::Relaxed) } == 0 {
        return; // REFCOUNT_STATIC_DATA
    }
    let prev = unsafe { (*rc).fetch_sub(1, Ordering::Release) };
    if prev == 1 {
        fence(Ordering::Acquire);
        if let Some(callback) = payload_decref {
            callback(data_ptr, roc_host as *const RocHost as *mut RocHost);
        }
        free_box_allocation(data, payload_alignment, payload_contains_refcounted, roc_host);
    }
}

/// Free a boxed payload allocation immediately after running payload teardown.
///
/// See `decref_box_with` for the meaning of `payload_contains_refcounted`.
///
/// # Safety
/// `data_ptr` must be a valid Roc box payload pointer that will not be used after this call.
pub unsafe fn free_box_with(
    data_ptr: RocBox,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    payload_decref: Option<RocBoxPayloadDecref>,
    roc_host: &RocHost,
) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    if let Some(callback) = payload_decref {
        callback(data_ptr, roc_host as *const RocHost as *mut RocHost);
    }
    free_box_allocation(data, payload_alignment, payload_contains_refcounted, roc_host);
}

/// Return true when a boxed payload data pointer has exactly one live ref.
pub fn is_unique_box(data_ptr: RocBox) -> bool {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return true,
    };
    let rc = box_refcount_ptr(data);
    unsafe { (*rc).load(Ordering::Acquire) == 1 }
}

fn box_data_ptr(data_ptr: RocBox) -> Option<*mut u8> {
    if data_ptr.is_null() {
        None
    } else {
        Some(data_ptr as *mut u8)
    }
}

fn box_refcount_ptr(data: *mut u8) -> *mut AtomicIsize {
    unsafe { data.sub(core::mem::size_of::<isize>()) as *mut AtomicIsize }
}

fn free_box_allocation(
    data: *mut u8,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: &RocHost,
) {
    let ptr_width = core::mem::size_of::<usize>();
    let required_space = if payload_contains_refcounted { checked_mul_usize(2, ptr_width, "Roc box header size overflow") } else { ptr_width };
    let header_bytes = required_space.max(payload_alignment);
    let alloc_alignment = ptr_width.max(payload_alignment);
    let base = unsafe { data.sub(header_bytes) } as *mut c_void;
    unsafe {
        roc_host.dealloc(base, alloc_alignment);
    }
}

/// A Roc string value. Small strings (up to 23 bytes on 64-bit) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `isize::MAX` bytes: about 2 GiB on 32-bit targets and 8 EiB on
/// 64-bit targets.
///
/// This type is ABI-compatible with the Zig RocStr (24 bytes, `#[repr(C)]`).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RocStr {
    pub bytes: *mut u8,
    pub capacity_or_alloc_ptr: usize,
    pub length: usize,
}

const _: () = assert!(core::mem::size_of::<RocStr>() == 3 * core::mem::size_of::<usize>(), "RocStr size mismatch");
const _: () = assert!(core::mem::align_of::<RocStr>() == core::mem::align_of::<usize>(), "RocStr alignment mismatch");
const _: () = assert!(core::mem::offset_of!(RocStr, bytes) == 0, "RocStr.bytes offset mismatch");
const _: () = assert!(core::mem::offset_of!(RocStr, capacity_or_alloc_ptr) == core::mem::size_of::<usize>(), "RocStr.capacity_or_alloc_ptr offset mismatch");
const _: () = assert!(core::mem::offset_of!(RocStr, length) == 2 * core::mem::size_of::<usize>(), "RocStr.length offset mismatch");

const ROC_STR_SIZE: usize = core::mem::size_of::<RocStr>();
const ROC_SMALL_STR_MAX_LEN: usize = ROC_STR_SIZE - 1;
const ROC_SMALL_STR_BIT: usize = isize::MIN as usize;
const ROC_SEAMLESS_SLICE_TAG: usize = 1;

impl RocStr {
    /// Return an empty RocStr (small string with zero length).
    pub fn empty() -> Self {
        Self {
            bytes: core::ptr::null_mut(),
            capacity_or_alloc_ptr: 0,
            length: ROC_SMALL_STR_BIT,
        }
    }

    /// Return true if this string is stored inline (small string optimization).
    #[inline]
    pub fn is_small_str(&self) -> bool {
        (self.length as isize) < 0
    }

    /// Return true if this string is a seamless slice into another allocation.
    #[inline]
    pub fn is_seamless_slice(&self) -> bool {
        !self.is_small_str() && (self.capacity_or_alloc_ptr & ROC_SEAMLESS_SLICE_TAG) != 0
    }

    /// Return the length of the string in bytes.
    #[inline]
    pub fn len(&self) -> usize {
        if self.is_small_str() {
            let bytes_ptr = self as *const Self as *const u8;
            let last_byte = unsafe { *bytes_ptr.add(ROC_STR_SIZE - 1) };
            (last_byte ^ 0b1000_0000) as usize
        } else {
            self.length
        }
    }

    /// Return true if the string has zero length.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Return the string contents as a byte slice.
    pub fn as_slice(&self) -> &[u8] {
        let ptr = self.as_u8_ptr();
        unsafe { core::slice::from_raw_parts(ptr, self.len()) }
    }

    /// Return a pointer to the raw UTF-8 bytes.
    #[inline]
    pub fn as_u8_ptr(&self) -> *const u8 {
        if self.is_small_str() {
            self as *const Self as *const u8
        } else {
            self.bytes as *const u8
        }
    }

    /// Return the string contents as a `&str`.
    pub fn as_str(&self) -> &str {
        core::str::from_utf8(self.as_slice()).expect("RocStr contained invalid UTF-8")
    }

    /// Create a RocStr from a UTF-8 byte slice, using `roc_host` for heap allocation if needed.
    pub fn from_slice(slice: &[u8], roc_host: &RocHost) -> Self {
        core::str::from_utf8(slice).expect("RocStr::from_slice requires valid UTF-8");
        if slice.len() < ROC_STR_SIZE {
            let mut result = Self::empty();
            let ptr = &mut result as *mut Self as *mut u8;
            unsafe {
                core::ptr::copy_nonoverlapping(slice.as_ptr(), ptr, slice.len());
                *ptr.add(ROC_STR_SIZE - 1) = (slice.len() as u8) | 0b1000_0000;
            }
            result
        } else {
            let ptr_width = core::mem::size_of::<usize>();
            let total = checked_add_usize(ptr_width, slice.len(), "RocStr allocation size overflow");
            let base = unsafe { roc_host.alloc(core::mem::align_of::<usize>(), total) };
            let data_ptr = unsafe { (base as *mut u8).add(ptr_width) };
            // Write refcount = 1
            unsafe {
                let rc = (data_ptr as *mut isize).sub(1);
                *rc = 1;
                core::ptr::copy_nonoverlapping(slice.as_ptr(), data_ptr, slice.len());
            }
            Self {
                bytes: data_ptr,
                capacity_or_alloc_ptr: shifted_capacity(slice.len()),
                length: slice.len(),
            }
        }
    }

    /// Create a RocStr from a `&str`.
    pub fn from_str(s: &str, roc_host: &RocHost) -> Self {
        Self::from_slice(s.as_bytes(), roc_host)
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    ///
    /// # Safety
    /// `self` must own one live Roc reference. Calling this more than once for the
    /// same ownership reference may double-free.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        if self.is_small_str() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        let rc = unsafe { (alloc_ptr as *mut AtomicIsize).sub(1) };
        if unsafe { (*rc).load(Ordering::Relaxed) } == 0 {
            return; // REFCOUNT_STATIC_DATA—bytes are in read-only memory
        }
        let prev = unsafe { (*rc).fetch_sub(1, Ordering::Release) };
        if prev == 1 {
            fence(Ordering::Acquire);
            let ptr_width = core::mem::size_of::<usize>();
            let base = unsafe { alloc_ptr.sub(ptr_width) } as *mut c_void;
            unsafe {
                roc_host.dealloc(base, core::mem::align_of::<usize>());
            }
        }
    }

    /// Increment the reference count by `amount`.
    ///
    /// # Safety
    /// `self` must point at a live Roc allocation. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        if self.is_small_str() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        let rc = unsafe { (alloc_ptr as *mut AtomicIsize).sub(1) };
        if unsafe { (*rc).load(Ordering::Relaxed) } == 0 {
            return; // REFCOUNT_STATIC_DATA
        }
        unsafe {
            (*rc).fetch_add(amount, Ordering::Relaxed);
        }
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn is_unique(&self) -> bool {
        if self.is_small_str() {
            return true;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return true;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            let count = (*rc).load(Ordering::Acquire);
            count == 0 || count == 1
        }
    }

    fn get_allocation_ptr(&self) -> *mut u8 {
        if self.is_seamless_slice() {
            (self.capacity_or_alloc_ptr & !ROC_SEAMLESS_SLICE_TAG) as *mut u8
        } else {
            self.bytes
        }
    }
}

impl core::fmt::Debug for RocStr {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("RocStr")
            .field("len", &self.len())
            .field("is_small", &self.is_small_str())
            .finish()
    }
}

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `ELEMENTS_REFCOUNTED` is true (the default via `RocList<T>`), an extra
/// `ptr_width` bytes are reserved in the allocation header for the element count,
/// matching the Roc runtime's `allocateWithRefcount` layout.
pub type RocList<T> = RocListWith<T, true>;

/// Parameterized list constructor; use `RocList<T>` for refcounted elements.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RocListWith<T, const ELEMENTS_REFCOUNTED: bool> {
    pub elements: *mut T,
    pub length: usize,
    pub capacity_or_alloc_ptr: usize,
}

const _: () = assert!(core::mem::size_of::<RocList<u8>>() == 3 * core::mem::size_of::<usize>(), "RocList size mismatch");
const _: () = assert!(core::mem::align_of::<RocList<u8>>() == core::mem::align_of::<usize>(), "RocList alignment mismatch");
const _: () = assert!(core::mem::offset_of!(RocList<u8>, elements) == 0, "RocList.elements offset mismatch");
const _: () = assert!(core::mem::offset_of!(RocList<u8>, length) == core::mem::size_of::<usize>(), "RocList.length offset mismatch");
const _: () = assert!(core::mem::offset_of!(RocList<u8>, capacity_or_alloc_ptr) == 2 * core::mem::size_of::<usize>(), "RocList.capacity_or_alloc_ptr offset mismatch");

impl<T, const ELEMENTS_REFCOUNTED: bool> RocListWith<T, ELEMENTS_REFCOUNTED> {
    #[inline]
    fn header_bytes() -> usize {
        let ptr_width = core::mem::size_of::<usize>();
        let required_space = if ELEMENTS_REFCOUNTED { checked_mul_usize(2, ptr_width, "RocList header size overflow") } else { ptr_width };
        required_space.max(core::mem::align_of::<T>())
    }

    /// Return an empty RocList.
    pub fn empty() -> Self {
        Self {
            elements: core::ptr::null_mut(),
            length: 0,
            capacity_or_alloc_ptr: 0,
        }
    }

    /// Return the number of elements in the list.
    #[inline]
    pub fn len(&self) -> usize {
        self.length
    }

    /// Return true if the list has zero elements.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.length == 0
    }

    /// Return true if this list is a seamless slice into another allocation.
    /// Slices share the rc slot with their backing allocation; the alloc ptr is
    /// encoded in `capacity_or_alloc_ptr` with the low bit set.
    #[inline]
    pub fn is_seamless_slice(&self) -> bool {
        (self.capacity_or_alloc_ptr & 1) != 0
    }

    /// Resolve `self` to the start of its backing allocation (the element block
    /// just after the rc slot). Returns `null` for empty lists. Handles both
    /// whole-backing and seamless-slice forms.
    fn get_allocation_ptr(&self) -> *mut u8 {
        if self.is_seamless_slice() {
            (self.capacity_or_alloc_ptr & !1) as *mut u8
        } else {
            self.elements as *mut u8
        }
    }

    fn allocation_element_count(&self) -> usize {
        if self.is_seamless_slice() && ELEMENTS_REFCOUNTED {
            let alloc_ptr = self.get_allocation_ptr();
            if alloc_ptr.is_null() {
                return 0;
            }
            unsafe {
                let ptr = alloc_ptr as *const usize;
                *ptr.sub(2)
            }
        } else {
            self.length
        }
    }

    /// Return the list elements as a slice.
    pub fn as_slice(&self) -> &[T] {
        if self.elements.is_null() {
            &[]
        } else {
            unsafe { core::slice::from_raw_parts(self.elements, self.length) }
        }
    }

    /// Return all items in the backing allocation, not just this slice.
    pub fn allocation_items(&self) -> &[T] {
        if self.elements.is_null() {
            &[]
        } else {
            unsafe { core::slice::from_raw_parts(self.get_allocation_ptr() as *const T, self.allocation_element_count()) }
        }
    }

    /// Allocate a new list with space for `length` elements.
    ///
    /// # Safety
    /// The returned element memory is uninitialized while `length` is already
    /// set. The caller must initialize every element before exposing the list
    /// to safe APIs, Roc code, or generated refcount helpers.
    pub unsafe fn allocate(length: usize, roc_host: &RocHost) -> Self {
        if length == 0 {
            return Self::empty();
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        let data_bytes = checked_mul_usize(length, core::mem::size_of::<T>(), "RocList allocation element bytes overflow");
        let total = checked_add_usize(data_bytes, header_bytes, "RocList allocation size overflow");
        let base = roc_host.alloc(align, total);
        let data_ptr = (base as *mut u8).add(header_bytes);
        unsafe {
            let rc = (data_ptr as *mut isize).sub(1);
            *rc = 1;
            if ELEMENTS_REFCOUNTED {
                let count = (data_ptr as *mut usize).sub(2);
                *count = length;
            }
        }
        Self {
            elements: data_ptr as *mut T,
            length,
            capacity_or_alloc_ptr: shifted_capacity(length),
        }
    }

    /// Create a RocList from a slice, copying elements into a new allocation.
    ///
    /// # Safety
    /// This is a shallow copy. For element types that own Roc references, the
    /// caller must ensure each copied element is already retained for the new
    /// list or will not be decref'd through another owner.
    pub unsafe fn from_slice(slice: &[T], roc_host: &RocHost) -> Self where T: Copy {
        if slice.is_empty() {
            return Self::empty();
        }
        let list = unsafe { Self::allocate(slice.len(), roc_host) };
        unsafe {
            core::ptr::copy_nonoverlapping(
                slice.as_ptr(),
                list.elements,
                slice.len(),
            );
        }
        list
    }

    /// Drop this reference to the list allocation, freeing it when this was the
    /// last one.
    ///
    /// Shallow: it never touches the elements. To release an owned list whose
    /// elements are refcounted, call that list's generated `decref_list_of_...`
    /// helper instead, which drops the elements when this reference is the last
    /// one and then calls this.
    ///
    /// # Safety
    /// `self` must own one live Roc list reference. Calling this more than once
    /// for the same ownership reference may double-free.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        if self.elements.is_null() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        let rc = unsafe { (alloc_ptr as *mut AtomicIsize).sub(1) };
        if unsafe { (*rc).load(Ordering::Relaxed) } == 0 {
            return; // REFCOUNT_STATIC_DATA—elements are in read-only memory
        }
        let prev = unsafe { (*rc).fetch_sub(1, Ordering::Release) };
        if prev == 1 {
            fence(Ordering::Acquire);
            let base = unsafe { alloc_ptr.sub(header_bytes) } as *mut c_void;
            unsafe {
                roc_host.dealloc(base, align);
            }
        }
    }

    /// Recursively release this list and its elements.
    ///
    /// The reference-count decrement claims the final reference atomically
    /// before reading any elements, so concurrent releases cannot skip or
    /// duplicate element teardown.
    ///
    /// # Safety
    /// `self` must own one live Roc list reference, and `P` must exactly
    /// describe how Roc releases one initialized `T` element.
    pub unsafe fn release_with<P>(self, roc_host: &RocHost)
    where
        P: RocRelease<T>,
    {
        if self.elements.is_null() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        let rc = unsafe { (alloc_ptr as *mut AtomicIsize).sub(1) };
        if unsafe { (*rc).load(Ordering::Relaxed) } == 0 {
            return; // REFCOUNT_STATIC_DATA—elements are in read-only memory
        }
        let prev = unsafe { (*rc).fetch_sub(1, Ordering::Release) };
        if prev == 1 {
            fence(Ordering::Acquire);
            if ELEMENTS_REFCOUNTED {
                for item_ref in self.allocation_items() {
                    let item = unsafe { core::ptr::read(item_ref) };
                    unsafe { P::release(item, roc_host); }
                }
            }
            let base = unsafe { alloc_ptr.sub(header_bytes) } as *mut c_void;
            unsafe { roc_host.dealloc(base, align); }
        }
    }

    /// Increment the reference count by `amount`.
    ///
    /// # Safety
    /// `self` must point at a live Roc list allocation. The retained references
    /// must be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        if self.elements.is_null() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        let rc = unsafe { (alloc_ptr as *mut AtomicIsize).sub(1) };
        if unsafe { (*rc).load(Ordering::Relaxed) } == 0 {
            return; // REFCOUNT_STATIC_DATA
        }
        unsafe {
            (*rc).fetch_add(amount, Ordering::Relaxed);
        }
    }

    /// Return true if this list has a reference count of exactly one.
    pub fn is_unique(&self) -> bool {
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return true;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            let count = (*rc).load(Ordering::Acquire);
            count == 0 || count == 1
        }
    }

    /// Return true if this list's allocation has exactly one counted ref.
    pub fn has_one_ref(&self) -> bool {
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return false;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            (*rc).load(Ordering::Acquire) == 1
        }
    }
}

impl<T: core::fmt::Debug, const ELEMENTS_REFCOUNTED: bool> core::fmt::Debug for RocListWith<T, ELEMENTS_REFCOUNTED> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_list().entries(self.as_slice().iter()).finish()
    }
}

/// Statically describes how to release one owned Roc ABI value of type `T`.
///
/// # Safety
/// Implementations must match Roc's exact allocation and nested ownership layout.
pub unsafe trait RocRelease<T> {
    unsafe fn release(value: T, roc_host: &RocHost);
}

/// An owning host-language wrapper around a value returned by Roc.
///
/// The release policy is zero-sized, so this wrapper adds no runtime metadata.
/// Dropping it recursively releases the value through the host's direct Roc
/// runtime symbols. Use `into_raw` to transfer ownership elsewhere.
#[repr(transparent)]
pub struct RocOwned<T, P: RocRelease<T>> {
    value: core::mem::ManuallyDrop<T>,
    policy: core::marker::PhantomData<P>,
}

impl<T, P: RocRelease<T>> RocOwned<T, P> {
    /// Take ownership of a raw value returned by a Roc-provided entrypoint.
    ///
    /// # Safety
    /// `value` must be one live owned result whose concrete release plan is `P`.
    pub unsafe fn from_raw(value: T) -> Self {
        Self { value: core::mem::ManuallyDrop::new(value), policy: core::marker::PhantomData }
    }

    pub fn as_ref(&self) -> &T {
        &self.value
    }

    /// Transfer ownership back to raw host code without releasing the value.
    pub fn into_raw(self) -> T {
        let mut this = core::mem::ManuallyDrop::new(self);
        unsafe { core::mem::ManuallyDrop::take(&mut this.value) }
    }
}

impl<T, P: RocRelease<T>> core::ops::Deref for RocOwned<T, P> {
    type Target = T;

    fn deref(&self) -> &T {
        self.as_ref()
    }
}

impl<T, P: RocRelease<T>> Drop for RocOwned<T, P> {
    fn drop(&mut self) {
        let value = unsafe { core::mem::ManuallyDrop::take(&mut self.value) };
        let roc_host = direct_roc_host();
        unsafe { P::release(value, &roc_host); }
    }
}

pub struct RocNoopRelease;

unsafe impl<T> RocRelease<T> for RocNoopRelease {
    unsafe fn release(_value: T, _roc_host: &RocHost) {}
}

pub struct RocStrRelease;

unsafe impl RocRelease<RocStr> for RocStrRelease {
    unsafe fn release(value: RocStr, roc_host: &RocHost) {
        unsafe { value.decref(roc_host); }
    }
}

pub struct RocListRelease<P>(core::marker::PhantomData<P>);

unsafe impl<T, P> RocRelease<RocListWith<T, true>> for RocListRelease<P>
where
    P: RocRelease<T>,
{
    unsafe fn release(value: RocListWith<T, true>, roc_host: &RocHost) {
        unsafe { value.release_with::<P>(roc_host); }
    }
}

pub struct RocListSpineRelease;

unsafe impl<T> RocRelease<RocListWith<T, false>> for RocListSpineRelease {
    unsafe fn release(value: RocListWith<T, false>, roc_host: &RocHost) {
        unsafe { value.decref(roc_host); }
    }
}

pub struct RocErasedCallableRelease;

unsafe impl RocRelease<RocErasedCallable> for RocErasedCallableRelease {
    unsafe fn release(value: RocErasedCallable, roc_host: &RocHost) {
        unsafe { decref_erased_callable(value, roc_host); }
    }
}

pub struct RocBoxRelease<T, P>(core::marker::PhantomData<(T, P)>);

extern "C" fn release_box_payload<T, P>(data_ptr: *mut c_void, roc_host: *mut RocHost)
where
    P: RocRelease<T>,
{
    if data_ptr.is_null() || roc_host.is_null() {
        return;
    }
    let value = unsafe { core::ptr::read(data_ptr as *const T) };
    unsafe { P::release(value, &*roc_host); }
}

unsafe impl<T, P> RocRelease<*mut T> for RocBoxRelease<T, P>
where
    P: RocRelease<T>,
{
    unsafe fn release(value: *mut T, roc_host: &RocHost) {
        unsafe {
            decref_box_with(
                value as RocBox,
                core::mem::align_of::<T>(),
                true,
                Some(release_box_payload::<T, P>),
                roc_host,
            );
        }
    }
}

pub struct RocBoxSpineRelease<T>(core::marker::PhantomData<T>);

unsafe impl<T> RocRelease<*mut T> for RocBoxSpineRelease<T> {
    unsafe fn release(value: *mut T, roc_host: &RocHost) {
        unsafe {
            decref_box_with(
                value as RocBox,
                core::mem::align_of::<T>(),
                false,
                None,
                roc_host,
            );
        }
    }
}

/// Element type for __AnonStruct_d10b67a07b7dbdef
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStructD10b67a07b7dbdef {
    pub root: u64,
    pub nodes: RocList<AnonStruct257fafdaa0a9c26e>,
}

/// Element type for __AnonStruct_d10b67a07b7dbdef
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStructD10b67a07b7dbdef {
    pub root: u64,
    pub nodes: RocList<AnonStruct257fafdaa0a9c26e>,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<AnonStructD10b67a07b7dbdef>() == 32, "AnonStructD10b67a07b7dbdef size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<AnonStructD10b67a07b7dbdef>() == 8, "AnonStructD10b67a07b7dbdef alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<AnonStructD10b67a07b7dbdef>() == 24, "AnonStructD10b67a07b7dbdef size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<AnonStructD10b67a07b7dbdef>() == 8, "AnonStructD10b67a07b7dbdef alignment mismatch");

/// Element type for __AnonStruct_257fafdaa0a9c26e
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct257fafdaa0a9c26e {
    pub id: u64,
    pub children: RocListWith<u64, false>,
    pub kind: ButtonOrColumnOrRowOrText,
}

/// Element type for __AnonStruct_257fafdaa0a9c26e
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct257fafdaa0a9c26e {
    pub id: u64,
    pub children: RocListWith<u64, false>,
    pub kind: ButtonOrColumnOrRowOrText,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<AnonStruct257fafdaa0a9c26e>() == 64, "AnonStruct257fafdaa0a9c26e size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<AnonStruct257fafdaa0a9c26e>() == 8, "AnonStruct257fafdaa0a9c26e alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<AnonStruct257fafdaa0a9c26e>() == 40, "AnonStruct257fafdaa0a9c26e size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<AnonStruct257fafdaa0a9c26e>() == 8, "AnonStruct257fafdaa0a9c26e alignment mismatch");

/// Element type for __AnonStruct_158f69ce56b55192
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct158f69ce56b55192 {
    pub old_root: u64,
    pub root: u64,
    pub nodes: RocList<AnonStruct257fafdaa0a9c26e>,
}

/// Element type for __AnonStruct_158f69ce56b55192
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct158f69ce56b55192 {
    pub old_root: u64,
    pub root: u64,
    pub nodes: RocList<AnonStruct257fafdaa0a9c26e>,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<AnonStruct158f69ce56b55192>() == 40, "AnonStruct158f69ce56b55192 size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<AnonStruct158f69ce56b55192>() == 8, "AnonStruct158f69ce56b55192 alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<AnonStruct158f69ce56b55192>() == 32, "AnonStruct158f69ce56b55192 size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<AnonStruct158f69ce56b55192>() == 8, "AnonStruct158f69ce56b55192 alignment mismatch");

/// Tag discriminant for MountOrNoChangeOrReplace.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MountOrNoChangeOrReplaceTag {
    Mount = 0,
    NoChange = 1,
    Replace = 2,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union MountOrNoChangeOrReplacePayload {
    pub mount: core::mem::ManuallyDrop<AnonStructD10b67a07b7dbdef>,
    pub no_change: [u8; 0],
    pub replace: core::mem::ManuallyDrop<AnonStruct158f69ce56b55192>,
}

#[cfg(target_pointer_width = "32")]
#[repr(align(8))]
#[derive(Clone, Copy)]
pub struct MountOrNoChangeOrReplacePayloadAlignment;

/// Tag union: MountOrNoChangeOrReplace
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct MountOrNoChangeOrReplace {
    pub _payload_alignment: [MountOrNoChangeOrReplacePayloadAlignment; 0],
    pub payload: [u8; 32],
    pub tag: MountOrNoChangeOrReplaceTag,
}

/// Tag union: MountOrNoChangeOrReplace
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct MountOrNoChangeOrReplace {
    pub payload: MountOrNoChangeOrReplacePayload,
    pub tag: MountOrNoChangeOrReplaceTag,
}

impl MountOrNoChangeOrReplace {
    /// Borrow the `Mount` payload without creating another owner.
    ///
    /// # Safety
    /// `self.tag` must be `MountOrNoChangeOrReplaceTag::Mount` and the payload must still be initialized.
    #[cfg(target_pointer_width = "32")]
    pub unsafe fn borrow_payload_mount_unchecked(&self) -> &AnonStructD10b67a07b7dbdef {
        unsafe { &*(self.payload.as_ptr() as *const AnonStructD10b67a07b7dbdef) }
    }

    /// Borrow the `Mount` payload without creating another owner.
    ///
    /// # Safety
    /// `self.tag` must be `MountOrNoChangeOrReplaceTag::Mount` and the payload must still be initialized.
    #[cfg(not(target_pointer_width = "32"))]
    pub unsafe fn borrow_payload_mount_unchecked(&self) -> &AnonStructD10b67a07b7dbdef {
        unsafe { &*(&self.payload.mount as *const core::mem::ManuallyDrop<AnonStructD10b67a07b7dbdef> as *const AnonStructD10b67a07b7dbdef) }
    }

    /// Move the `Mount` payload out of one owned tag-union shell.
    ///
    /// # Safety
    /// `self.tag` must be `MountOrNoChangeOrReplaceTag::Mount`. After this call, `self` is logically uninitialized and must not be read or destroyed.
    #[cfg(target_pointer_width = "32")]
    pub unsafe fn take_payload_mount_unchecked(&mut self) -> AnonStructD10b67a07b7dbdef {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const AnonStructD10b67a07b7dbdef) }
    }

    /// Move the `Mount` payload out of one owned tag-union shell.
    ///
    /// # Safety
    /// `self.tag` must be `MountOrNoChangeOrReplaceTag::Mount`. After this call, `self` is logically uninitialized and must not be read or destroyed.
    #[cfg(not(target_pointer_width = "32"))]
    pub unsafe fn take_payload_mount_unchecked(&mut self) -> AnonStructD10b67a07b7dbdef {
        unsafe { core::mem::ManuallyDrop::take(&mut self.payload.mount) }
    }

    /// Borrow the `Replace` payload without creating another owner.
    ///
    /// # Safety
    /// `self.tag` must be `MountOrNoChangeOrReplaceTag::Replace` and the payload must still be initialized.
    #[cfg(target_pointer_width = "32")]
    pub unsafe fn borrow_payload_replace_unchecked(&self) -> &AnonStruct158f69ce56b55192 {
        unsafe { &*(self.payload.as_ptr() as *const AnonStruct158f69ce56b55192) }
    }

    /// Borrow the `Replace` payload without creating another owner.
    ///
    /// # Safety
    /// `self.tag` must be `MountOrNoChangeOrReplaceTag::Replace` and the payload must still be initialized.
    #[cfg(not(target_pointer_width = "32"))]
    pub unsafe fn borrow_payload_replace_unchecked(&self) -> &AnonStruct158f69ce56b55192 {
        unsafe { &*(&self.payload.replace as *const core::mem::ManuallyDrop<AnonStruct158f69ce56b55192> as *const AnonStruct158f69ce56b55192) }
    }

    /// Move the `Replace` payload out of one owned tag-union shell.
    ///
    /// # Safety
    /// `self.tag` must be `MountOrNoChangeOrReplaceTag::Replace`. After this call, `self` is logically uninitialized and must not be read or destroyed.
    #[cfg(target_pointer_width = "32")]
    pub unsafe fn take_payload_replace_unchecked(&mut self) -> AnonStruct158f69ce56b55192 {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const AnonStruct158f69ce56b55192) }
    }

    /// Move the `Replace` payload out of one owned tag-union shell.
    ///
    /// # Safety
    /// `self.tag` must be `MountOrNoChangeOrReplaceTag::Replace`. After this call, `self` is logically uninitialized and must not be read or destroyed.
    #[cfg(not(target_pointer_width = "32"))]
    pub unsafe fn take_payload_replace_unchecked(&mut self) -> AnonStruct158f69ce56b55192 {
        unsafe { core::mem::ManuallyDrop::take(&mut self.payload.replace) }
    }

}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<MountOrNoChangeOrReplace>() == 48, "MountOrNoChangeOrReplace size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<MountOrNoChangeOrReplace>() == 8, "MountOrNoChangeOrReplace alignment mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::offset_of!(MountOrNoChangeOrReplace, tag) == 40, "MountOrNoChangeOrReplace tag offset mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<MountOrNoChangeOrReplace>() == 40, "MountOrNoChangeOrReplace size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<MountOrNoChangeOrReplace>() == 8, "MountOrNoChangeOrReplace alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::offset_of!(MountOrNoChangeOrReplace, tag) == 32, "MountOrNoChangeOrReplace tag offset mismatch");

/// Tag discriminant for ButtonOrColumnOrRowOrText.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ButtonOrColumnOrRowOrTextTag {
    Button = 0,
    Column = 1,
    Row = 2,
    Text = 3,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union ButtonOrColumnOrRowOrTextPayload {
    pub button: [u8; 0],
    pub column: [u8; 0],
    pub row: [u8; 0],
    pub text: core::mem::ManuallyDrop<RocStr>,
}

#[cfg(target_pointer_width = "32")]
#[repr(align(4))]
#[derive(Clone, Copy)]
pub struct ButtonOrColumnOrRowOrTextPayloadAlignment;

/// Tag union: ButtonOrColumnOrRowOrText
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct ButtonOrColumnOrRowOrText {
    pub _payload_alignment: [ButtonOrColumnOrRowOrTextPayloadAlignment; 0],
    pub payload: [u8; 12],
    pub tag: ButtonOrColumnOrRowOrTextTag,
}

/// Tag union: ButtonOrColumnOrRowOrText
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct ButtonOrColumnOrRowOrText {
    pub payload: ButtonOrColumnOrRowOrTextPayload,
    pub tag: ButtonOrColumnOrRowOrTextTag,
}

impl ButtonOrColumnOrRowOrText {
    /// Borrow the `Text` payload without creating another owner.
    ///
    /// # Safety
    /// `self.tag` must be `ButtonOrColumnOrRowOrTextTag::Text` and the payload must still be initialized.
    #[cfg(target_pointer_width = "32")]
    pub unsafe fn borrow_payload_text_unchecked(&self) -> &RocStr {
        unsafe { &*(self.payload.as_ptr() as *const RocStr) }
    }

    /// Borrow the `Text` payload without creating another owner.
    ///
    /// # Safety
    /// `self.tag` must be `ButtonOrColumnOrRowOrTextTag::Text` and the payload must still be initialized.
    #[cfg(not(target_pointer_width = "32"))]
    pub unsafe fn borrow_payload_text_unchecked(&self) -> &RocStr {
        unsafe { &*(&self.payload.text as *const core::mem::ManuallyDrop<RocStr> as *const RocStr) }
    }

    /// Move the `Text` payload out of one owned tag-union shell.
    ///
    /// # Safety
    /// `self.tag` must be `ButtonOrColumnOrRowOrTextTag::Text`. After this call, `self` is logically uninitialized and must not be read or destroyed.
    #[cfg(target_pointer_width = "32")]
    pub unsafe fn take_payload_text_unchecked(&mut self) -> RocStr {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const RocStr) }
    }

    /// Move the `Text` payload out of one owned tag-union shell.
    ///
    /// # Safety
    /// `self.tag` must be `ButtonOrColumnOrRowOrTextTag::Text`. After this call, `self` is logically uninitialized and must not be read or destroyed.
    #[cfg(not(target_pointer_width = "32"))]
    pub unsafe fn take_payload_text_unchecked(&mut self) -> RocStr {
        unsafe { core::mem::ManuallyDrop::take(&mut self.payload.text) }
    }

}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<ButtonOrColumnOrRowOrText>() == 32, "ButtonOrColumnOrRowOrText size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<ButtonOrColumnOrRowOrText>() == 8, "ButtonOrColumnOrRowOrText alignment mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::offset_of!(ButtonOrColumnOrRowOrText, tag) == 24, "ButtonOrColumnOrRowOrText tag offset mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<ButtonOrColumnOrRowOrText>() == 16, "ButtonOrColumnOrRowOrText size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<ButtonOrColumnOrRowOrText>() == 4, "ButtonOrColumnOrRowOrText alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::offset_of!(ButtonOrColumnOrRowOrText, tag) == 12, "ButtonOrColumnOrRowOrText tag offset mismatch");

/// Arguments for Host.apply!
/// Roc signature: [Mount({ nodes : List({ children : List(U64), id : U64, kind : [Button, Column, Row, Text(Str)] }), root : U64 }), NoChange, Replace({ nodes : List({ children : List(U64), id : U64, kind : [Button, Column, Row, Text(Str)] }), old_root : U64, root : U64 })] => {}
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostApplyArgs {
    pub arg0: MountOrNoChangeOrReplace,
}

/// Arguments for Host.set_dispatch!
/// Roc signature: Box(U64 => {}) => {}
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostSetDispatchArgs {
    pub arg0: RocErasedCallable,
}

// Platform Type Aliases

pub type MountOrNoChangeOrReplaceMount = AnonStructD10b67a07b7dbdef;
pub type MountOrNoChangeOrReplaceReplace = AnonStruct158f69ce56b55192;
pub type MountOrNoChangeOrReplaceMountNodes = AnonStruct257fafdaa0a9c26e;
pub type MountOrNoChangeOrReplaceReplaceNodes = AnonStruct257fafdaa0a9c26e;

// Generated Refcount Helpers

impl MountOrNoChangeOrReplace {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let mut value = self;
        let _ = roc_host;
        match value.tag {
            MountOrNoChangeOrReplaceTag::Mount => {
                let payload = unsafe { value.take_payload_mount_unchecked() };
                unsafe { payload.decref(roc_host); }
            },
            MountOrNoChangeOrReplaceTag::NoChange => {},
            MountOrNoChangeOrReplaceTag::Replace => {
                let payload = unsafe { value.take_payload_replace_unchecked() };
                unsafe { payload.decref(roc_host); }
            },
        }
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        let _ = amount;
        match value.tag {
            MountOrNoChangeOrReplaceTag::Mount => {
                let payload = unsafe { core::ptr::read(value.borrow_payload_mount_unchecked()) };
                unsafe { payload.incref(amount); }
            },
            MountOrNoChangeOrReplaceTag::NoChange => {},
            MountOrNoChangeOrReplaceTag::Replace => {
                let payload = unsafe { core::ptr::read(value.borrow_payload_replace_unchecked()) };
                unsafe { payload.incref(amount); }
            },
        }
    }
}

pub struct MountOrNoChangeOrReplaceRelease;

unsafe impl RocRelease<MountOrNoChangeOrReplace> for MountOrNoChangeOrReplaceRelease {
    unsafe fn release(value: MountOrNoChangeOrReplace, roc_host: &RocHost) {
        unsafe { value.decref(roc_host); }
    }
}

impl AnonStructD10b67a07b7dbdef {
    /// Recursively decrement Roc-owned fields.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted field.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        unsafe { decref_list_of_anon_struct257fafdaa0a9c26e(value.nodes, roc_host); }
    }

    /// Increment Roc-owned fields.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        unsafe { value.nodes.incref(amount); }
    }
}

pub struct AnonStructD10b67a07b7dbdefRelease;

unsafe impl RocRelease<AnonStructD10b67a07b7dbdef> for AnonStructD10b67a07b7dbdefRelease {
    unsafe fn release(value: AnonStructD10b67a07b7dbdef, roc_host: &RocHost) {
        unsafe { value.decref(roc_host); }
    }
}

impl AnonStruct257fafdaa0a9c26e {
    /// Recursively decrement Roc-owned fields.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted field.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        unsafe { value.children.decref(roc_host); }
        unsafe { value.kind.decref(roc_host); }
    }

    /// Increment Roc-owned fields.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        unsafe { value.children.incref(amount); }
        unsafe { value.kind.incref(amount); }
    }
}

pub struct AnonStruct257fafdaa0a9c26eRelease;

unsafe impl RocRelease<AnonStruct257fafdaa0a9c26e> for AnonStruct257fafdaa0a9c26eRelease {
    unsafe fn release(value: AnonStruct257fafdaa0a9c26e, roc_host: &RocHost) {
        unsafe { value.decref(roc_host); }
    }
}

impl ButtonOrColumnOrRowOrText {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let mut value = self;
        let _ = roc_host;
        match value.tag {
            ButtonOrColumnOrRowOrTextTag::Button => {},
            ButtonOrColumnOrRowOrTextTag::Column => {},
            ButtonOrColumnOrRowOrTextTag::Row => {},
            ButtonOrColumnOrRowOrTextTag::Text => {
                let payload = unsafe { value.take_payload_text_unchecked() };
                unsafe { payload.decref(roc_host); }
            },
        }
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        let _ = amount;
        match value.tag {
            ButtonOrColumnOrRowOrTextTag::Button => {},
            ButtonOrColumnOrRowOrTextTag::Column => {},
            ButtonOrColumnOrRowOrTextTag::Row => {},
            ButtonOrColumnOrRowOrTextTag::Text => {
                let payload = unsafe { core::ptr::read(value.borrow_payload_text_unchecked()) };
                unsafe { payload.incref(amount); }
            },
        }
    }
}

pub struct ButtonOrColumnOrRowOrTextRelease;

unsafe impl RocRelease<ButtonOrColumnOrRowOrText> for ButtonOrColumnOrRowOrTextRelease {
    unsafe fn release(value: ButtonOrColumnOrRowOrText, roc_host: &RocHost) {
        unsafe { value.decref(roc_host); }
    }
}

impl AnonStruct158f69ce56b55192 {
    /// Recursively decrement Roc-owned fields.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted field.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        unsafe { decref_list_of_anon_struct257fafdaa0a9c26e(value.nodes, roc_host); }
    }

    /// Increment Roc-owned fields.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        unsafe { value.nodes.incref(amount); }
    }
}

pub struct AnonStruct158f69ce56b55192Release;

unsafe impl RocRelease<AnonStruct158f69ce56b55192> for AnonStruct158f69ce56b55192Release {
    unsafe fn release(value: AnonStruct158f69ce56b55192, roc_host: &RocHost) {
        unsafe { value.decref(roc_host); }
    }
}

/// Release one owned reference to a `RocList<AnonStruct257fafdaa0a9c26e>`.
///
/// The allocation's final reference is claimed atomically before any element
/// is read, so concurrent owners cannot skip or duplicate element teardown.
///
/// # Safety
/// `value` must own one live Roc list reference.
pub unsafe fn decref_list_of_anon_struct257fafdaa0a9c26e(value: RocList<AnonStruct257fafdaa0a9c26e>, roc_host: &RocHost) {
    unsafe { value.release_with::<AnonStruct257fafdaa0a9c26eRelease>(roc_host); }
}


// Runtime Symbols
//
// The host defines these linker symbols. Compiled Roc code calls them directly.

#[allow(improper_ctypes)]
unsafe extern "C" {
    pub fn roc_alloc(length: usize, alignment: usize) -> *mut c_void;
    pub fn roc_dealloc(ptr: *mut c_void, alignment: usize);
    pub fn roc_realloc(ptr: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void;
    pub fn roc_dbg(bytes: *const u8, len: usize);
    pub fn roc_expect_failed(bytes: *const u8, len: usize);
    pub fn roc_crashed(bytes: *const u8, len: usize);
}

extern "C" fn direct_roc_alloc(_host: *mut RocHost, length: usize, alignment: usize) -> *mut c_void {
    unsafe { roc_alloc(length, alignment) }
}

extern "C" fn direct_roc_dealloc(_host: *mut RocHost, ptr: *mut c_void, alignment: usize) {
    unsafe { roc_dealloc(ptr, alignment); }
}

extern "C" fn direct_roc_realloc(_host: *mut RocHost, ptr: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void {
    unsafe { roc_realloc(ptr, new_length, alignment) }
}

extern "C" fn direct_roc_dbg(_host: *mut RocHost, bytes: *const u8, len: usize) {
    unsafe { roc_dbg(bytes, len); }
}

extern "C" fn direct_roc_expect_failed(_host: *mut RocHost, bytes: *const u8, len: usize) {
    unsafe { roc_expect_failed(bytes, len); }
}

extern "C" fn direct_roc_crashed(_host: *mut RocHost, bytes: *const u8, len: usize) {
    unsafe { roc_crashed(bytes, len); }
}

fn direct_roc_host() -> RocHost {
    RocHost {
        env: core::ptr::null_mut(),
        roc_alloc: direct_roc_alloc,
        roc_dealloc: direct_roc_dealloc,
        roc_realloc: direct_roc_realloc,
        roc_dbg: direct_roc_dbg,
        roc_expect_failed: direct_roc_expect_failed,
        roc_crashed: direct_roc_crashed,
    }
}

// Hosted Symbols
//
// The platform host must export these symbols with the exact direct C ABI signatures.
// Refcounted arguments are owned by the hosted function.

#[allow(improper_ctypes)]
unsafe extern "C" {
    /// Hosted symbol for Host.apply!
    /// Roc signature: [Mount({ nodes : List({ children : List(U64), id : U64, kind : [Button, Column, Row, Text(Str)] }), root : U64 }), NoChange, Replace({ nodes : List({ children : List(U64), id : U64, kind : [Button, Column, Row, Text(Str)] }), old_root : U64, root : U64 })] => {}
    /// Owned arguments. Release each exactly once before returning, unless it is
    /// moved into storage or into the result:
    ///     unsafe { arg0.decref(roc_host); }
    pub fn roc_gui_apply(arg0: MountOrNoChangeOrReplace);

    /// Hosted symbol for Host.set_dispatch!
    /// Roc signature: Box(U64 => {}) => {}
    /// Owned arguments. Release each exactly once before returning, unless it is
    /// moved into storage or into the result:
    ///     unsafe { decref_erased_callable(arg0, roc_host); }
    pub fn roc_gui_set_dispatch(arg0: RocErasedCallable);

}

/// Default memory management functions for Roc platform helpers.
///
/// Memory layout: each allocation prepends size metadata so that dealloc/realloc
/// can recover the original allocation size because `roc_dealloc` receives no length.
#[cfg(not(no_roc_std_helpers))]
pub struct DefaultAllocators;

#[cfg(not(no_roc_std_helpers))]
impl DefaultAllocators {
    /// Allocate memory using the Rust global allocator.
    pub extern "C" fn roc_alloc(_roc_host: *mut RocHost, length: usize, alignment: usize) -> *mut c_void {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;
            let total_size = checked_add_usize(length, size_storage_bytes, "roc_alloc allocation size overflow");

            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let layout = Layout::from_size_align_unchecked(total_size, min_alignment);
            let base_ptr = std::alloc::alloc(layout);
            if base_ptr.is_null() {
                eprintln!("roc_alloc: out of memory");
                std::process::exit(1);
            }

            let size_ptr = base_ptr.add(size_storage_bytes).sub(core::mem::size_of::<usize>()) as *mut usize;
            *size_ptr = total_size;

            base_ptr.add(size_storage_bytes) as *mut c_void
        }
    }

    /// Free memory previously allocated by `roc_alloc`.
    pub extern "C" fn roc_dealloc(_roc_host: *mut RocHost, ptr: *mut c_void, alignment: usize) {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;

            let size_ptr = (ptr as *const u8).sub(core::mem::size_of::<usize>()) as *const usize;
            let total_size = *size_ptr;

            let base_ptr = (ptr as *mut u8).sub(size_storage_bytes);
            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let layout = Layout::from_size_align_unchecked(total_size, min_alignment);
            std::alloc::dealloc(base_ptr, layout);
        }
    }

    /// Reallocate memory, preserving existing user data.
    pub extern "C" fn roc_realloc(_roc_host: *mut RocHost, ptr: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;

            let old_size_ptr = (ptr as *const u8).sub(core::mem::size_of::<usize>()) as *const usize;
            let old_total_size = *old_size_ptr;
            let old_base_ptr = (ptr as *mut u8).sub(size_storage_bytes);

            let new_total_size = checked_add_usize(new_length, size_storage_bytes, "roc_realloc allocation size overflow");
            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let old_layout = Layout::from_size_align_unchecked(old_total_size, min_alignment);
            let new_base_ptr = std::alloc::realloc(old_base_ptr, old_layout, new_total_size);
            if new_base_ptr.is_null() {
                eprintln!("roc_realloc: out of memory");
                std::process::exit(1);
            }

            let new_user_ptr = new_base_ptr.add(size_storage_bytes);
            let new_size_ptr = new_user_ptr.sub(core::mem::size_of::<usize>()) as *mut usize;
            *new_size_ptr = new_total_size;
            new_user_ptr as *mut c_void
        }
    }
}

/// Default handlers for dbg, expect-failed, and crash.
#[cfg(not(no_roc_std_helpers))]
pub struct DefaultHandlers;

#[cfg(not(no_roc_std_helpers))]
impl DefaultHandlers {
    /// Print a `dbg` expression to stderr.
    pub extern "C" fn roc_dbg(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC DBG] {}", msg);
        }
    }

    /// Print a failed `expect` to stderr.
    pub extern "C" fn roc_expect_failed(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC EXPECT] {}", msg);
        }
    }

    /// Print a `crash` message to stderr and exit.
    pub extern "C" fn roc_crashed(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC CRASHED] {}", msg);
            std::process::exit(1);
        }
    }
}

/// Create a host-internal helper context with default memory management and handlers.
///
/// This is only for helper functions in this generated file. It is not passed to
/// compiled Roc code, which uses the direct symbol ABI declared above.
#[cfg(not(no_roc_std_helpers))]
pub fn make_roc_host(env: *mut c_void) -> RocHost {
    RocHost {
        env,
        roc_alloc: DefaultAllocators::roc_alloc,
        roc_dealloc: DefaultAllocators::roc_dealloc,
        roc_realloc: DefaultAllocators::roc_realloc,
        roc_dbg: DefaultHandlers::roc_dbg,
        roc_expect_failed: DefaultHandlers::roc_expect_failed,
        roc_crashed: DefaultHandlers::roc_crashed,
    }
}

// Provided Symbols
//
// Roc exports these symbols from the app with their natural C ABI signatures.

#[allow(improper_ctypes)]
unsafe extern "C" {
    /// Entrypoint: gui_init!
    pub fn roc_gui_init();

    /// Entrypoint: gui_dispatch!
    pub fn roc_gui_dispatch(arg0: RocErasedCallable, arg1: u64);

}

