import Action
import Work
import Session
import Resource
import InternalHttp

Host := [].{
	Patch : [Mount({ root : U64 }), NoChange, Replace({ old_root : U64, root : U64 })]

	node_text! : Str => U64

	node_styled_text! : { value : Str, fg : U64, font_size : U32, font_weight : U32, font_face : U8, runs : List({ len : U64, fg : U64, bg : U64, font_weight : U32, underline : Bool, monospace : Bool }) } => U64

	children_begin! : () => U64

	children_push! : U64, U64 => {}
	keyed_seed! : { container : U64, revision : U64, keys : List(List(U8)) } => {}
	keyed_edit_begin! : { container : U64, base_revision : U64, new_revision : U64 } => {}
	keyed_insert_before! : { key : List(U8), before : List(U8), root : U64 } => {}
	keyed_remove! : List(U8) => {}
	keyed_move_before! : { key : List(U8), before : List(U8) } => {}
	keyed_set! : { key : List(U8), root : U64 } => {}
	keyed_edit_commit! : () => {}
	component_work! : U8, U64 => {}
	node_boundary! : U64, U64 => U64
	retain_subtree! : U64 => U64
	begin_render! : U64 => {}
	scope_enter! : U8, Str, U64 => {}
	scope_exit! : () => {}
	component_resolve! : U8, List(U8) => { instance : U64, root : U64 }
	component_enter! : U64 => {}
	component_exit! : () => {}

	node_row! : {
		builder : U64,
		label : Str,
		gap : U32,
		padding_top : U32,
		padding_right : U32,
		padding_bottom : U32,
		padding_left : U32,
		width_kind : U8,
		width : U32,
		height_kind : U8,
		height : U32,
		min_width_kind : U8,
		min_width : U32,
		min_height_kind : U8,
		min_height : U32,
		max_width_kind : U8,
		max_width : U32,
		max_height_kind : U8,
		max_height : U32,
		grow : Bool,
		bg : U64,
		hover_bg : U64,
		active_bg : U64,
		disabled_bg : U64,
		disabled_fg : U64,
		focus_color : U64,
		fg : U64,
		border_color : U64,
		border_top : U32,
		border_right : U32,
		border_bottom : U32,
		border_left : U32,
		radius : U32,
		font_size : U32,
		font_weight : U32,
		shadow : U32,
		shadow_y : U32,
		shadow_color : U64,
		shadow_alpha : U32,
		font_face : U8,
		text_overflow : U8,
		overflow_x : U8,
		overflow_y : U8,
		align : U8,
		justify : U8,
	} => U64

	node_column! : {
		builder : U64,
		label : Str,
		gap : U32,
		padding_top : U32,
		padding_right : U32,
		padding_bottom : U32,
		padding_left : U32,
		width_kind : U8,
		width : U32,
		height_kind : U8,
		height : U32,
		min_width_kind : U8,
		min_width : U32,
		min_height_kind : U8,
		min_height : U32,
		max_width_kind : U8,
		max_width : U32,
		max_height_kind : U8,
		max_height : U32,
		grow : Bool,
		bg : U64,
		hover_bg : U64,
		active_bg : U64,
		disabled_bg : U64,
		disabled_fg : U64,
		focus_color : U64,
		fg : U64,
		border_color : U64,
		border_top : U32,
		border_right : U32,
		border_bottom : U32,
		border_left : U32,
		radius : U32,
		font_size : U32,
		font_weight : U32,
		shadow : U32,
		shadow_y : U32,
		shadow_color : U64,
		shadow_alpha : U32,
		font_face : U8,
		text_overflow : U8,
		overflow_x : U8,
		overflow_y : U8,
		align : U8,
		justify : U8,
	} => U64
	node_dialog! : {
		builder : U64,
		label : Str,
		gap : U32,
		padding_top : U32,
		padding_right : U32,
		padding_bottom : U32,
		padding_left : U32,
		width_kind : U8,
		width : U32,
		height_kind : U8,
		height : U32,
		min_width_kind : U8,
		min_width : U32,
		min_height_kind : U8,
		min_height : U32,
		max_width_kind : U8,
		max_width : U32,
		max_height_kind : U8,
		max_height : U32,
		grow : Bool,
		bg : U64,
		hover_bg : U64,
		active_bg : U64,
		disabled_bg : U64,
		disabled_fg : U64,
		focus_color : U64,
		fg : U64,
		border_color : U64,
		border_top : U32,
		border_right : U32,
		border_bottom : U32,
		border_left : U32,
		radius : U32,
		font_size : U32,
		font_weight : U32,
		shadow : U32,
		shadow_y : U32,
		shadow_color : U64,
		shadow_alpha : U32,
		font_face : U8,
		text_overflow : U8,
		overflow_x : U8,
		overflow_y : U8,
		align : U8,
		justify : U8,
	} => U64
	node_popover! : {
		builder : U64,
		label : Str,
		placement : U8,
		delay_ms : U32,
		hover_enter : Bool,
		hover_exit : Bool,
		shortcuts : List({ keys : Str, focus : Bool }),
		focus_serial : U64,
		gap : U32,
		padding_top : U32,
		padding_right : U32,
		padding_bottom : U32,
		padding_left : U32,
		width_kind : U8,
		width : U32,
		height_kind : U8,
		height : U32,
		min_width_kind : U8,
		min_width : U32,
		min_height_kind : U8,
		min_height : U32,
		max_width_kind : U8,
		max_width : U32,
		max_height_kind : U8,
		max_height : U32,
		grow : Bool,
		bg : U64,
		hover_bg : U64,
		active_bg : U64,
		disabled_bg : U64,
		disabled_fg : U64,
		focus_color : U64,
		fg : U64,
		border_color : U64,
		border_top : U32,
		border_right : U32,
		border_bottom : U32,
		border_left : U32,
		radius : U32,
		font_size : U32,
		font_weight : U32,
		shadow : U32,
		shadow_y : U32,
		shadow_color : U64,
		shadow_alpha : U32,
		font_face : U8,
		text_overflow : U8,
		overflow_x : U8,
		overflow_y : U8,
		align : U8,
		justify : U8,
	} => { id : U64, hover_enter : U64, hover_exit : U64, shortcut : U64 }

	node_panel! : {
		builder : U64,
		label : Str,
		gap : U32,
		padding_top : U32,
		padding_right : U32,
		padding_bottom : U32,
		padding_left : U32,
		width_kind : U8,
		width : U32,
		height_kind : U8,
		height : U32,
		min_width_kind : U8,
		min_width : U32,
		min_height_kind : U8,
		min_height : U32,
		max_width_kind : U8,
		max_width : U32,
		max_height_kind : U8,
		max_height : U32,
		grow : Bool,
		bg : U64,
		hover_bg : U64,
		active_bg : U64,
		disabled_bg : U64,
		disabled_fg : U64,
		focus_color : U64,
		fg : U64,
		border_color : U64,
		border_top : U32,
		border_right : U32,
		border_bottom : U32,
		border_left : U32,
		radius : U32,
		font_size : U32,
		font_weight : U32,
		shadow : U32,
		shadow_y : U32,
		shadow_color : U64,
		shadow_alpha : U32,
		font_face : U8,
		text_overflow : U8,
		overflow_x : U8,
		overflow_y : U8,
		align : U8,
		justify : U8,
	} => U64
	node_scroll! : {
		axis : U8,
		child : U64,
		name : Str,
		gap : U32,
		padding_top : U32,
		padding_right : U32,
		padding_bottom : U32,
		padding_left : U32,
		width_kind : U8,
		width : U32,
		height_kind : U8,
		height : U32,
		min_width_kind : U8,
		min_width : U32,
		min_height_kind : U8,
		min_height : U32,
		max_width_kind : U8,
		max_width : U32,
		max_height_kind : U8,
		max_height : U32,
		grow : Bool,
		bg : U64,
		hover_bg : U64,
		active_bg : U64,
		disabled_bg : U64,
		disabled_fg : U64,
		focus_color : U64,
		fg : U64,
		border_color : U64,
		border_top : U32,
		border_right : U32,
		border_bottom : U32,
		border_left : U32,
		radius : U32,
		font_size : U32,
		font_weight : U32,
		shadow : U32,
		shadow_y : U32,
		shadow_color : U64,
		shadow_alpha : U32,
		font_face : U8,
		text_overflow : U8,
		overflow_x : U8,
		overflow_y : U8,
		align : U8,
		justify : U8,
	} => U64

	node_action_button! : {
		caption : Str,
		label : Str,
		role : U8,
		enabled : Bool,
		hover_enter : Bool,
		hover_exit : Bool,
		gap : U32,
		padding_top : U32,
		padding_right : U32,
		padding_bottom : U32,
		padding_left : U32,
		width_kind : U8,
		width : U32,
		height_kind : U8,
		height : U32,
		min_width_kind : U8,
		min_width : U32,
		min_height_kind : U8,
		min_height : U32,
		max_width_kind : U8,
		max_width : U32,
		max_height_kind : U8,
		max_height : U32,
		grow : Bool,
		bg : U64,
		hover_bg : U64,
		active_bg : U64,
		disabled_bg : U64,
		disabled_fg : U64,
		focus_color : U64,
		fg : U64,
		border_color : U64,
		border_top : U32,
		border_right : U32,
		border_bottom : U32,
		border_left : U32,
		radius : U32,
		font_size : U32,
		font_weight : U32,
		shadow : U32,
		shadow_y : U32,
		shadow_color : U64,
		shadow_alpha : U32,
		font_face : U8,
		text_overflow : U8,
		overflow_x : U8,
		overflow_y : U8,
		align : U8,
		justify : U8,
	} => { id : U64, hover_enter : U64, hover_exit : U64 }

	node_virtual_item! : U64, U64 => U64

	node_virtual_list! : {
		builder : U64,
		count : U64,
		first : U64,
		instance : U64,
		notify : Bool,
		name : Str,
		row_height : U32,
		row_gap : U32,
		gap : U32,
		padding_top : U32,
		padding_right : U32,
		padding_bottom : U32,
		padding_left : U32,
		width_kind : U8,
		width : U32,
		height_kind : U8,
		height : U32,
		min_width_kind : U8,
		min_width : U32,
		min_height_kind : U8,
		min_height : U32,
		max_width_kind : U8,
		max_width : U32,
		max_height_kind : U8,
		max_height : U32,
		grow : Bool,
		bg : U64,
		hover_bg : U64,
		active_bg : U64,
		disabled_bg : U64,
		disabled_fg : U64,
		focus_color : U64,
		fg : U64,
		border_color : U64,
		border_top : U32,
		border_right : U32,
		border_bottom : U32,
		border_left : U32,
		radius : U32,
		font_size : U32,
		font_weight : U32,
		shadow : U32,
		shadow_y : U32,
		shadow_color : U64,
		shadow_alpha : U32,
		font_face : U8,
		text_overflow : U8,
		overflow_x : U8,
		overflow_y : U8,
		align : U8,
		justify : U8,
	} => U64

	node_checkbox! : {
		label : Str,
		checked : Bool,
		enabled : Bool,
		box_bg : U64,
		box_checked_bg : U64,
		box_border : U64,
		mark_color : U64,
		gap : U32,
		padding_top : U32,
		padding_right : U32,
		padding_bottom : U32,
		padding_left : U32,
		width_kind : U8,
		width : U32,
		height_kind : U8,
		height : U32,
		min_width_kind : U8,
		min_width : U32,
		min_height_kind : U8,
		min_height : U32,
		max_width_kind : U8,
		max_width : U32,
		max_height_kind : U8,
		max_height : U32,
		grow : Bool,
		bg : U64,
		hover_bg : U64,
		active_bg : U64,
		disabled_bg : U64,
		disabled_fg : U64,
		focus_color : U64,
		fg : U64,
		border_color : U64,
		border_top : U32,
		border_right : U32,
		border_bottom : U32,
		border_left : U32,
		radius : U32,
		font_size : U32,
		font_weight : U32,
		shadow : U32,
		shadow_y : U32,
		shadow_color : U64,
		shadow_alpha : U32,
		font_face : U8,
		text_overflow : U8,
		overflow_x : U8,
		overflow_y : U8,
		align : U8,
		justify : U8,
	} => U64

	node_textarea! : {
		label : Str,
		value : Str,
		placeholder : Str,
		enabled : Bool,
		read_only : Bool,
		gap : U32,
		padding_top : U32,
		padding_right : U32,
		padding_bottom : U32,
		padding_left : U32,
		width_kind : U8,
		width : U32,
		height_kind : U8,
		height : U32,
		min_width_kind : U8,
		min_width : U32,
		min_height_kind : U8,
		min_height : U32,
		max_width_kind : U8,
		max_width : U32,
		max_height_kind : U8,
		max_height : U32,
		grow : Bool,
		bg : U64,
		hover_bg : U64,
		active_bg : U64,
		disabled_bg : U64,
		disabled_fg : U64,
		focus_color : U64,
		fg : U64,
		border_color : U64,
		border_top : U32,
		border_right : U32,
		border_bottom : U32,
		border_left : U32,
		radius : U32,
		font_size : U32,
		font_weight : U32,
		shadow : U32,
		shadow_y : U32,
		shadow_color : U64,
		shadow_alpha : U32,
		font_face : U8,
		text_overflow : U8,
		overflow_x : U8,
		overflow_y : U8,
		align : U8,
		justify : U8,
	} => U64

	node_image! : {
		label : Str,
		bytes : List(U8),
		format : U8,
		fit : U8,
		grayscale : Bool,
		gap : U32,
		padding_top : U32,
		padding_right : U32,
		padding_bottom : U32,
		padding_left : U32,
		width_kind : U8,
		width : U32,
		height_kind : U8,
		height : U32,
		min_width_kind : U8,
		min_width : U32,
		min_height_kind : U8,
		min_height : U32,
		max_width_kind : U8,
		max_width : U32,
		max_height_kind : U8,
		max_height : U32,
		grow : Bool,
		bg : U64,
		hover_bg : U64,
		active_bg : U64,
		disabled_bg : U64,
		disabled_fg : U64,
		focus_color : U64,
		fg : U64,
		border_color : U64,
		border_top : U32,
		border_right : U32,
		border_bottom : U32,
		border_left : U32,
		radius : U32,
		font_size : U32,
		font_weight : U32,
		shadow : U32,
		shadow_y : U32,
		shadow_color : U64,
		shadow_alpha : U32,
		font_face : U8,
		text_overflow : U8,
		overflow_x : U8,
		overflow_y : U8,
		align : U8,
		justify : U8,
	} => U64

	node_canvas! : {
		label : Str,
		primitives : List({ kind : U8, key : U64, label : Str, x : I32, y : I32, width : U32, height : U32, x2 : I32, y2 : I32, fill : U64, stroke : U64, stroke_width : U32, radius : U32, text : Str, text_size : U32, align : U8 }),
		width_kind : U8,
		width : U32,
		height_kind : U8,
		height : U32,
		grow : Bool,
		bg : U64,
		border_color : U64,
		border_width : U32,
		radius : U32,
		hover : Bool,
		wheel : Bool,
		size : Bool,
	} => U64

	virtual_window! : { instance : U64, count : U64, row_height : U32, scroll_row : U64, scroll_align : U8, scroll_serial : U64 } => { first : U64, end : U64 }
	virtual_rows_event! : () => { refresh : Bool, report : Bool, start : U64, end : U64 }
	canvas_event! : () => { phase : U8, x : I32, y : I32, dx : I32, dy : I32, target : U64 }
	shortcut_event! : () => { index : U64, keys : Str }
	node_split! : {
		builder : U64,
		label : Str,
		axis : U8,
		side : U8,
		size : U32,
		min : U32,
		max : U32,
		collapsible : Bool,
		collapsed : Bool,
		thickness : U32,
		keys : List({ keys : Str, focus : Bool }),
		gap : U32,
		padding_top : U32,
		padding_right : U32,
		padding_bottom : U32,
		padding_left : U32,
		width_kind : U8,
		width : U32,
		height_kind : U8,
		height : U32,
		min_width_kind : U8,
		min_width : U32,
		min_height_kind : U8,
		min_height : U32,
		max_width_kind : U8,
		max_width : U32,
		max_height_kind : U8,
		max_height : U32,
		grow : Bool,
		bg : U64,
		hover_bg : U64,
		active_bg : U64,
		disabled_bg : U64,
		disabled_fg : U64,
		focus_color : U64,
		fg : U64,
		border_color : U64,
		border_top : U32,
		border_right : U32,
		border_bottom : U32,
		border_left : U32,
		radius : U32,
		font_size : U32,
		font_weight : U32,
		shadow : U32,
		shadow_y : U32,
		shadow_color : U64,
		shadow_alpha : U32,
		font_face : U8,
		text_overflow : U8,
		overflow_x : U8,
		overflow_y : U8,
		align : U8,
		justify : U8,
	} => { id : U64, shortcut : U64 }
	resize_event! : () => { size : U32, collapsed : Bool }

	node_text_input! : {
		label : Str,
		value : Str,
		placeholder : Str,
		enabled : Bool,
		gap : U32,
		padding_top : U32,
		padding_right : U32,
		padding_bottom : U32,
		padding_left : U32,
		width_kind : U8,
		width : U32,
		height_kind : U8,
		height : U32,
		min_width_kind : U8,
		min_width : U32,
		min_height_kind : U8,
		min_height : U32,
		max_width_kind : U8,
		max_width : U32,
		max_height_kind : U8,
		max_height : U32,
		grow : Bool,
		bg : U64,
		hover_bg : U64,
		active_bg : U64,
		disabled_bg : U64,
		disabled_fg : U64,
		focus_color : U64,
		fg : U64,
		border_color : U64,
		border_top : U32,
		border_right : U32,
		border_bottom : U32,
		border_left : U32,
		radius : U32,
		font_size : U32,
		font_weight : U32,
		shadow : U32,
		shadow_y : U32,
		shadow_color : U64,
		shadow_alpha : U32,
		font_face : U8,
		text_overflow : U8,
		overflow_x : U8,
		overflow_y : U8,
		align : U8,
		justify : U8,
	} => { change : U64, id : U64, submit : U64 }

	input_value! : () => Str

	sqlite_open_read! : Resource.DirRead, Str => Try(Resource.SqliteRead, { code : U8, message : Str })
	sqlite_open_file_read! : Resource.FileRead => Try(Resource.SqliteRead, { code : U8, message : Str })
	sqlite_watch! : Resource.SqliteRead => Try(Resource.Watch, { code : U8, message : Str })
	sqlite_query! : Resource.SqliteRead, { sql : Str, params : List({ bytes : List(U8), integer : I64, kind : U8, real : F64, text : Str }), page_rows : U64 } => Try({ columns : List(Str), rows : List(List({ bytes : List(U8), integer : I64, kind : U8, real : F64, text : Str })), more : Bool }, { code : U8, message : Str })
	clipboard_acquire! : () => Try(Resource.Clipboard, { code : U8, message : Str })
	clipboard_read_text! : Resource.Clipboard => Try({ sequence : U64, text : Str }, { code : U8, message : Str })
	clipboard_write_text! : Resource.Clipboard, Str => Try({}, { code : U8, message : Str })
	process_acquire! : () => Try(Resource.ProcessGrant, [AcquireProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), CancelProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), ReadProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), ResizeProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), SpawnProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), WriteProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported])])
	process_spawn! : Resource.ProcessGrant, { columns : U16, rows : U16 } => Try(Resource.Pty, [AcquireProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), CancelProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), ReadProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), ResizeProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), SpawnProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), WriteProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported])])
	process_read! : Resource.Pty, U32 => Try([Canceled, Data(List(U8)), EndOfFile], [AcquireProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), CancelProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), ReadProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), ResizeProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), SpawnProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), WriteProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported])])
	process_write! : Resource.Pty, List(U8) => Try(U32, [AcquireProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), CancelProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), ReadProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), ResizeProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), SpawnProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), WriteProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported])])
	process_resize! : Resource.Pty, { columns : U16, rows : U16 } => Try({}, [AcquireProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), CancelProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), ReadProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), ResizeProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), SpawnProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), WriteProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported])])
	process_cancel! : Resource.Pty => Try([AlreadyStopped, Canceled], [AcquireProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), CancelProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), ReadProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), ResizeProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), SpawnProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported]), WriteProcessErr([AccessDenied, Busy, Exited, InvalidCapability, InvalidSize, Io, ResourceLimit, Revoked, Unsupported])])
	device_acquire! : () => Try(Resource.DeviceGrant, [AcquireDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), CloseDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), ConnectDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), DiscoverDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), TransactDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported])])
	device_discover! : Resource.DeviceGrant => Try(List({ manufacturer : Str, product : Str, product_id : U16, vendor_id : U16 }), [AcquireDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), CloseDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), ConnectDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), DiscoverDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), TransactDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported])])
	device_connect! : Resource.DeviceGrant => Try(Resource.DeviceConnection, [AcquireDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), CloseDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), ConnectDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), DiscoverDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), TransactDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported])])
	device_transact! : Resource.DeviceConnection, List(U8) => Try(List(U8), [AcquireDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), CloseDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), ConnectDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), DiscoverDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), TransactDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported])])
	device_close! : Resource.DeviceConnection => Try({}, [AcquireDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), CloseDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), ConnectDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), DiscoverDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported]), TransactDeviceErr([AccessDenied, Busy, Closed, Disconnected, InvalidCapability, InvalidRequest, Io, NotFound, Protocol, ResourceLimit, Revoked, Timeout, Unsupported])])

	system_acquire! : () => Try(Resource.SystemSampler, U8)
	system_sample! : Resource.SystemSampler => Try({ cpu_available : Bool, cpu_tenths : U16, disk_available : Bool, disk_read_bytes : U64, disk_written_bytes : U64, memory_available : Bool, memory_total_bytes : U64, memory_used_bytes : U64, network_available : Bool, network_received_bytes : U64, network_transmitted_bytes : U64, processes : List({ cpu_tenths : U16, memory_bytes : U64, name : Str, pid : U64 }), processes_available : Bool, sequence : U64 }, U8)
	system_close! : Resource.SystemSampler => Try({}, U8)
	image_inspect! : List(U8), U8 => Try({ height : U32, width : U32 }, U8)
	assets_open! : { root_kind : U8, root : Str, manifest_required : Bool, asset_set : Str, schema : U32, content_version : U32, content_mode : U8, content_hash : Str } => Try(Resource.AssetStore, U8)
	assets_read! : Resource.AssetStore, Str => Try(List(U8), U8)

	audio_acquire! : () => Try(Resource.AudioOutput, { code : U8, message : Str })
	audio_load! : Resource.AudioOutput, Resource.DirRead, Str => Try({ duration_ms : U64, track : Resource.AudioTrack }, { code : U8, message : Str })
	audio_play! : Resource.AudioTrack => Try({}, { code : U8, message : Str })
	audio_pause! : Resource.AudioTrack => Try({}, { code : U8, message : Str })
	audio_seek! : Resource.AudioTrack, U64 => Try({}, { code : U8, message : Str })
	audio_status! : Resource.AudioTrack => Try({ duration_ms : U64, position_ms : U64, state : U8 }, { code : U8, message : Str })
	audio_stop! : Resource.AudioTrack => Try({}, { code : U8, message : Str })

	tcp_connect! : () => Try(Resource.TcpStream, U8)
	tcp_read_up_to! : Resource.TcpStream, U64 => Try(List(U8), U8)
	tcp_write_all! : Resource.TcpStream, List(U8) => Try({}, U8)
	tcp_close! : Resource.TcpStream => Try({}, U8)

	apply! : Patch => {}

	set_dispatch! : Box((Session(a) => {})) => {}

	task_complete! : Box(Action.Completion(a)) => {}
	enqueue_task! : U64, Str, Box(() => Work) => {}
	cancel_task! : U64, Str => {}

	timer_start! : U64 => Resource.Timer

	timer_next! : Resource.Timer => Bool

	timer_cancel! : Resource.Timer => Bool

	http_acquire! : () => Try(Resource.HttpClient, [AccessDenied, BodyTooLarge, ConnectFailed, InvalidCapability, InvalidHeader, InvalidRequest, InvalidUrl, RedirectLimit, Revoked, Timeout, UnsupportedScheme])
	http_send! : InternalHttp.HostRequest => Try(InternalHttp.HostResponse, [AccessDenied, BodyTooLarge, ConnectFailed, InvalidCapability, InvalidHeader, InvalidRequest, InvalidUrl, RedirectLimit, Revoked, Timeout, UnsupportedScheme])

	work_start! : U8 => {}

	work_end! : U8 => {}

	window_config! : Str, U32, U32, U64, U64 => {}

	appearance_current! : () => U8

	appearance_next_change! : U8 => U8

	appearance_prefer! : U8 => {}
}
