(test "browse and transform a capability-scoped image"
  (grants
    (directory "fixture"))
  (steps
    (expect-image-owner-counters 0 0 0 0)
    (click (role button :name "Open image folder"))
    (await-task)
    (expect-file-picks 1)
    (expect-file-lists 1)
    (expect-file-reads 26)
    (expect-visible (text "27 of 27 entries"))
    (expect-image-owner-counters 25 5644 26 1)
    (replace-text (role textbox :name "Filter images") "corrupt.svg")
    (expect-visible (text "corrupt.svg — Corrupt image"))
    (replace-text (role textbox :name "Filter images") "sunset.svg")
    (click (role button :name "View image sunset.svg"))
    (expect-visible (role image :name "Selected image"))
    (expect-image-bytes (role image :name "Selected image") 396)
    (expect-visible (text "320 × 180 pixels; 396 encoded bytes"))
    (expect-image-owner-counters 28 6832 26 1)
    (click (role button :name "Show actual image size"))
    (expect-visible (text "View: Actual size"))))
