(test "the scrollback filter narrows to nothing and is reversible"
  (grants
    (process test-program))
  (steps
    (expect-visible (text "0/0 lines"))
    (expect-visible (text "filter off"))
    (replace-text (role textbox :name "Search terminal") "nothing yet")
    (expect-visible (text "0/0 lines"))
    (expect-not-visible (text "filter off"))
    (replace-text (role textbox :name "Search terminal") "")
    (expect-visible (text "filter off"))
    (click (role button :name "New terminal"))
    (await-task)
    (await-task)
    (replace-text (role textbox :name "Terminal command") "alpha")
    (submit (role textbox :name "Terminal command"))
    (await-task)
    (await-task)
    (expect-visible (text-prefix "Terminal line: echo:alpha"))
    (expect-visible (text-prefix "Terminal line: terminal-ready"))
    (replace-text (role textbox :name "Search terminal") "no-such-line")
    (expect-count (text-prefix "Terminal line: ") 0)
    (expect-not-visible (text "filter off"))
    (expect-visible (text "Session active"))
    (replace-text (role textbox :name "Search terminal") "")
    (expect-visible (text-prefix "Terminal line: echo:alpha"))
    (expect-visible (text-prefix "Terminal line: terminal-ready"))
    (expect-visible (text "filter off"))
    (click (role button :name "Stop terminal"))
    (await-task)
    (await-task)
    (expect-processes 0)))
