(test "a stopped session starts again from its rest state"
  (steps
    (expect-visible (text "No session"))
    (expect-visible (text "gen 0"))
    (expect-visible (text "0/0 lines"))
    (expect-processes 0)
    (click (role button :name "New terminal"))
    (await-task)
    (await-task)
    (expect-visible (text "Session active"))
    (expect-visible (text "gen 1"))
    (expect-visible (text-prefix "Terminal line: terminal-ready"))
    (click (role button :name "Stop terminal"))
    (await-task)
    (await-task)
    (expect-visible (text "Session canceled"))
    (expect-visible (text "gen 2"))
    (expect-processes 0)
    (expect-visible (text-prefix "Terminal line: terminal-ready"))
    (click (role button :name "New terminal"))
    (await-task)
    (expect-processes 1)
    (await-task)
    (expect-visible (text "Session active"))
    (expect-visible (text "gen 3"))
    (replace-text (role textbox :name "Terminal command") "hello")
    (submit (role textbox :name "Terminal command"))
    (await-task)
    (await-task)
    (expect-visible (text-prefix "Terminal line: echo:hello"))
    (click (role button :name "Stop terminal"))
    (await-task)
    (await-task)
    (expect-visible (text "Session canceled"))
    (expect-visible (text "gen 4"))
    (expect-processes 0)))
