(test "scrollback search filters terminal output"
  (grants
    (process test-program))
  (steps
    (click (role button :name "New terminal"))
    (await-task)
    (await-task)
    (replace-text (role textbox :name "Terminal command") "alpha")
    (submit (role textbox :name "Terminal command"))
    (await-task)
    (await-task)
    (replace-text (role textbox :name "Terminal command") "beta")
    (submit (role textbox :name "Terminal command"))
    (await-task)
    (await-task)
    (replace-text (role textbox :name "Search terminal") "echo:beta")
    (expect-visible (text-prefix "Terminal line: echo:beta"))
    (expect-not-visible (text-prefix "Terminal line: echo:alpha"))
    (click (role button :name "Stop terminal"))
    (await-task)
    (await-task)
    (expect-processes 0)))
