(test "Two nested workspaces own independent live PTYs and task completions"
  (grants
    (process test-program))
  (steps
    (click (role button :name "Split workspace"))
    (expect-processes 0)
    (click (within (role column :name "Primary workspace") (role button :name "New terminal")))
    (await-task)
    (await-task)
    (expect-processes 1)
    (expect-visible (within (role column :name "Primary workspace") (text-prefix "terminal-ready")))
    (click (within (role column :name "Secondary workspace") (role button :name "New terminal")))
    (await-task)
    (await-task)
    (expect-processes 2)
    (expect-visible (within (role column :name "Secondary workspace") (text-prefix "terminal-ready")))

    (replace-text (within (role column :name "Primary workspace") (role textbox :name "Terminal command")) "primary-only")
    (submit (within (role column :name "Primary workspace") (role textbox :name "Terminal command")))
    (await-task)
    (await-task)
    (expect-visible (within (role column :name "Primary workspace") (text-prefix "echo:primary-only")))
    (expect-not-visible (within (role column :name "Secondary workspace") (text-prefix "echo:primary-only")))
    (replace-text (within (role column :name "Secondary workspace") (role textbox :name "Terminal command")) "secondary-only")
    (submit (within (role column :name "Secondary workspace") (role textbox :name "Terminal command")))
    (await-task)
    (await-task)
    (expect-visible (within (role column :name "Secondary workspace") (text-prefix "echo:secondary-only")))
    (expect-not-visible (within (role column :name "Primary workspace") (text-prefix "echo:secondary-only")))

    (click (within (role column :name "Primary workspace") (role button :name "Stop terminal")))
    (await-task)
    (await-task)
    (expect-visible (within (role column :name "Primary workspace") (text "Session canceled")))
    (expect-processes 1)
    (replace-text (within (role column :name "Secondary workspace") (role textbox :name "Terminal command")) "still-live")
    (submit (within (role column :name "Secondary workspace") (role textbox :name "Terminal command")))
    (await-task)
    (await-task)
    (expect-visible (within (role column :name "Secondary workspace") (text-prefix "echo:still-live")))
    (expect-visible (within (role column :name "Primary workspace") (text "Session canceled")))
    (expect-processes 1)
    (click (within (role column :name "Secondary workspace") (role button :name "Stop terminal")))
    (await-task)
    (await-task)
    (expect-visible (within (role column :name "Secondary workspace") (text "Session canceled")))
    (expect-processes 0)))
