(test "the instrument panel presents its regions, its signal status, and dense scrollback"
  (steps
    (settle)
    (expect-on-screen (role row :name "Workspace header"))
    (expect-on-screen (role row :name "Session controls"))
    (expect-on-screen (role row :name "Command bar"))
    (expect-on-screen (role row :name "Filter bar"))
    (expect-on-screen (role column :name "Scrollback well"))
    (expect-on-screen (role row :name "Workspace footer"))
    (screenshot "idle")
    (click (role button :name "New terminal"))
    (await-task)
    (await-task)
    ; A terminal answers on its own schedule, not the window's: wait for more
    ; quiet frames than a repaint needs, so its first output is in hand.
    (settle :frames 8)
    (expect-visible (text "Session active"))
    (screenshot "session")
    (focus (role textbox :name "Terminal command"))
    (type "lines:40")
    (key "enter")
    (await-task)
    (await-task)
    (settle :frames 8)
    (expect-on-screen (text-prefix "Terminal line: line-000001"))
    (screenshot "dense")
    (screenshot "footer" :region (role row :name "Workspace footer") :pad 4)
    (click (role button :name "Stop terminal"))
    (await-task)
    (await-task)
    (settle :frames 8)
    (expect-visible (text "Session canceled"))))
