#!/usr/bin/env python3
"""Build and test xkbcommon source in a pinned Linux builder, without a host build."""

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import tarfile

import dependency_archive
import nix_link_inputs
from dependency_archive import digest, write_archive
from dependency_artifacts import sha256, unpack_verified

ROOT = Path(__file__).resolve().parents[1]
RECIPE = ROOT / "dependencies/xkbcommon.json"

ARCHIVE_NAME = "xkbcommon-x64glibc.tar"


def verify_source(path, source):
    if (path.is_symlink() or path.stat().st_size != source["size"]
            or sha256(path) != source["sha256"]):
        raise ValueError("xkbcommon source differs from the reviewed recipe")


def check_candidate(archive, source, output, compiler):
    """Execute a keyboard-map probe against the extracted candidate library.

    This runs in the producer before attestation. Archive bytes are generated by
    this build, and the normal consumer inventory verifier checks extraction.
    The probe's headers come from the same verified upstream source archive.
    """
    candidate = output / "candidate"
    unpack_verified(archive, {"name": "xkbcommon", "target": "x64glibc"}, candidate)
    library_dir = candidate / "targets/x64glibc"
    # Only the probe's private runtime search tree needs a SONAME symlink. The
    # distributable archive contains regular files and has no filesystem links.
    for name in ("libxkbcommon", "libxkbcommon-x11"):
        (library_dir / (name + ".so.0")).symlink_to(name + ".so")
    executable = output / "xkbcommon-probe"
    subprocess.run([
        *compiler, "-I" + str(source / "include"),
        str(ROOT / "test/dependencies/xkbcommon.c"),
        str(library_dir / "libxkbcommon.so"), str(library_dir / "libxkbcommon-x11.so"),
        "-Wl,-rpath," + str(library_dir), "-o", str(executable),
    ], check=True, timeout=60)
    environment = os.environ.copy()
    environment.pop("LD_LIBRARY_PATH", None)
    environment.pop("LD_PRELOAD", None)
    subprocess.run(nix_link_inputs.probe_command(executable), check=True, env=environment, timeout=15)


def inside_builder(source_archive, output):
    """Compile with networking disabled inside the Nix sandbox."""
    recipe_bytes = RECIPE.read_bytes()
    recipe = json.loads(recipe_bytes)
    zig = "zig"
    version = subprocess.check_output([zig, "version"], text=True).strip()
    if version != recipe["zig_version"]:
        raise ValueError("xkbcommon producer requires the recipe's exact Zig version")
    compiler = [zig, *recipe["cc_args"]]
    verify_source(source_archive, recipe["source"])
    source_root = Path.cwd() / "source"
    with tarfile.open(source_archive) as packed:
        packed.extractall(source_root, filter="data")
    source = source_root / recipe["source"]["directory"]
    build = Path.cwd() / "build"
    meson = ["meson"]
    meson_version = subprocess.check_output([*meson, "--version"], text=True).strip()
    if meson_version != recipe["meson_version"]:
        raise ValueError("xkbcommon producer requires the recipe's exact Meson version")
    machine = Path.cwd() / "zig.ini"
    machine.write_text((ROOT / "dependencies/xkbcommon/zig.ini").read_text().replace(
        "@PROBE_WRAPPER@", repr(nix_link_inputs.probe_command("")[:-1])))
    subprocess.run([*meson, "setup", str(build), str(source),
                    "--cross-file=" + str(machine),
                    *recipe["meson_options"]], check=True, timeout=120)
    libraries = ("libxkbcommon", "libxkbcommon-x11")
    sonames = [name + ".so.0.13.2" for name in libraries]
    subprocess.run(["ninja", "-C", str(build), "-j2", *sonames], check=True, timeout=900)
    installed = Path.cwd() / "installed"
    subprocess.run([*meson, "install", "-C", str(build), "--no-rebuild",
                    "--destdir", str(installed)], check=True, timeout=60)
    for soname in sonames:
        nix_link_inputs.portable_library(installed / "usr/lib" / soname)
    files = {"targets/x64glibc/" + name + ".so":
             (installed / "usr/lib" / soname).read_bytes()
             for name, soname in zip(libraries, sonames)}
    files["licenses/xkbcommon/LICENSE"] = (source / "LICENSE").read_bytes()
    files.update(nix_link_inputs.sources("xkbcommon"))
    files["sources/xkbcommon/source.tar.gz"] = source_archive.read_bytes()
    for path in (
        'dependencies/xkbcommon.json',
        'scripts/build_xkbcommon.py',
        'scripts/dependency_archive.py',
        'scripts/dependency_artifacts.py',
        'test/dependencies/xkbcommon.c',
        'dependencies/xkbcommon/zig.ini',
        'dependencies/xkbcommon/cc.sh',
    ):
        files["sources/xkbcommon/" + path] = (ROOT / path).read_bytes()
    metadata = {
        "schema_version": 2, "name": recipe["name"], "version": recipe["version"],
        "target": recipe["target"], "source": recipe["source"],
        "build": {
            **nix_link_inputs.provenance(),
            "toolchain_sha256": sha256(ROOT / "dependencies/xkbcommon/zig.ini"),
            "compiler_adapter_sha256": sha256(ROOT / "dependencies/xkbcommon/cc.sh"),
           "recipe_sha256": digest(recipe_bytes),
            "producer_sha256": sha256(Path(__file__)),
            "archive_writer_sha256": sha256(Path(dependency_archive.__file__)),
            "probe_sha256": sha256(ROOT / "test/dependencies/xkbcommon.c"),
            "zig_version": version,
            "cc_args": recipe["cc_args"],
            "meson_options": recipe["meson_options"],
            "compiler": subprocess.check_output([*compiler, "--version"], text=True).splitlines()[0],
            "meson": meson_version,
        },
    }
    # Keep the candidate private until its exact bytes pass the native probe.
    archive = write_archive(build / ARCHIVE_NAME, metadata, files)
    check_candidate(archive, source, build, compiler)
    shutil.copyfile(archive, output / ARCHIVE_NAME)


def build(output, *, rebuild=False):
    return nix_link_inputs.build("xkbcommon", output, rebuild=rebuild)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--inside", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument("--rebuild", action="store_true", help="force Nix to rebuild and check reproducibility")
    args = parser.parse_args()
    if args.inside:
        inside_builder(Path(os.environ["NIX_COMPONENT_SOURCE"]), args.output)
    else:
        build(args.output.resolve(), rebuild=args.rebuild)
