#!/usr/bin/env python3
"""Build and test FreeType source in a pinned Linux builder, without a host build."""

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import tarfile

import dependency_archive
import nix_link_inputs
from dependency_archive import digest, write_archive
from dependency_artifacts import sha256, unpack_verified

ROOT = Path(__file__).resolve().parents[1]
RECIPE = ROOT / "dependencies/freetype.json"

ARCHIVE_NAME = "freetype-x64glibc.tar"


def verify_source(path, source):
    if (path.is_symlink() or path.stat().st_size != source["size"]
            or sha256(path) != source["sha256"]):
        raise ValueError("FreeType source differs from the reviewed recipe")


def check_candidate(archive, source, output, compiler):
    """Execute a glyph-rendering probe against the extracted candidate library.

    This runs in the producer before attestation. Archive bytes are generated by
    this build, and the normal consumer inventory verifier checks extraction.
    The probe's headers come from the same verified upstream source archive.
    """
    candidate = output / "candidate"
    unpack_verified(archive, {"name": "freetype", "target": "x64glibc"}, candidate)
    library_dir = candidate / "targets/x64glibc"
    # Only the probe's private runtime search tree needs a SONAME symlink. The
    # distributable archive contains regular files and has no filesystem links.
    (library_dir / "libfreetype.so.6").symlink_to("libfreetype.so")
    executable = output / "freetype-probe"
    subprocess.run([
        *compiler, "-I" + str(source / "include"),
        str(ROOT / "test/dependencies/freetype.c"),
        str(library_dir / "libfreetype.so"),
        "-Wl,-rpath," + str(library_dir), "-o", str(executable),
    ], check=True, timeout=60)
    environment = os.environ.copy()
    environment.pop("LD_LIBRARY_PATH", None)
    environment.pop("LD_PRELOAD", None)
    subprocess.run(nix_link_inputs.probe_command(executable), check=True, env=environment, timeout=15)


def inside_builder(source_archive, output):
    """Compile with networking disabled inside the Nix sandbox."""
    recipe_bytes = RECIPE.read_bytes()
    recipe = json.loads(recipe_bytes)
    zig = "zig"
    version = subprocess.check_output([zig, "version"], text=True).strip()
    if version != recipe["zig_version"]:
        raise ValueError("FreeType producer requires the recipe's exact Zig version")
    compiler = [zig, *recipe["cc_args"]]
    verify_source(source_archive, recipe["source"])
    source_root = Path.cwd() / "source"
    with tarfile.open(source_archive) as packed:
        packed.extractall(source_root, filter="data")
    source = source_root / recipe["source"]["directory"]
    build = Path.cwd() / "build"
    subprocess.run(["cmake", "-S", str(source), "-B", str(build),
                    "-DCMAKE_TOOLCHAIN_FILE=" + str(ROOT / "dependencies/linux/zig-toolchain.cmake"),
                    *recipe["cmake_options"]], check=True, timeout=120)
    subprocess.run(["cmake", "--build", str(build), "--parallel", "2"],
                   check=True, timeout=900)
    nix_link_inputs.portable_library(build / "libfreetype.so")
    files = {"targets/x64glibc/libfreetype.so": (build / "libfreetype.so").read_bytes()}
    for name in ("LICENSE.TXT", "docs/FTL.TXT", "docs/GPLv2.TXT"):
        files["licenses/freetype/" + Path(name).name] = (source / name).read_bytes()
    files["licenses/freetype/NOTICE"] = (
        "This software is based in part on the work of the FreeType Team.\n"
        "FreeType is distributed here under the FreeType License (FTL.TXT).\n"
    ).encode()
    files.update(nix_link_inputs.sources("freetype"))
    files["sources/freetype/source.tar.xz"] = source_archive.read_bytes()
    for path in (
        'dependencies/freetype.json',
        'scripts/build_freetype.py',
        'scripts/dependency_archive.py',
        'scripts/dependency_artifacts.py',
        'test/dependencies/freetype.c',
        'dependencies/linux/zig-toolchain.cmake',
    ):
        files["sources/freetype/" + path] = (ROOT / path).read_bytes()
    metadata = {
        "schema_version": 2, "name": recipe["name"], "version": recipe["version"],
        "target": recipe["target"], "source": recipe["source"],
        "build": {
            **nix_link_inputs.provenance(),
            "toolchain_sha256": sha256(ROOT / "dependencies/linux/zig-toolchain.cmake"),
           "recipe_sha256": digest(recipe_bytes),
            "producer_sha256": sha256(Path(__file__)),
            "archive_writer_sha256": sha256(Path(dependency_archive.__file__)),
            "probe_sha256": sha256(ROOT / "test/dependencies/freetype.c"),
            "zig_version": version,
            "cc_args": recipe["cc_args"],
            "cmake_options": recipe["cmake_options"],
            "compiler": subprocess.check_output([*compiler, "--version"], text=True).splitlines()[0],
            "cmake": subprocess.check_output(["cmake", "--version"], text=True).splitlines()[0],
        },
    }
    # Keep the candidate private until its exact bytes pass the native probe.
    archive = write_archive(build / ARCHIVE_NAME, metadata, files)
    check_candidate(archive, source, build, compiler)
    shutil.copyfile(archive, output / ARCHIVE_NAME)


def build(output, *, rebuild=False):
    return nix_link_inputs.build("freetype", output, rebuild=rebuild)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--inside", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument("--rebuild", action="store_true", help="force Nix to rebuild and check reproducibility")
    args = parser.parse_args()
    if args.inside:
        inside_builder(Path(os.environ["NIX_COMPONENT_SOURCE"]), args.output)
    else:
        build(args.output.resolve(), rebuild=args.rebuild)
