#!/usr/bin/env python3
"""Build and test xkbcommon source in a pinned Linux builder, without a host build."""

import argparse
import json
import os
from pathlib import Path
import platform
import shutil
import subprocess
import tarfile
import tempfile
from urllib.request import urlopen

import dependency_archive
from dependency_archive import digest, write_archive
from dependency_artifacts import sha256, unpack_verified

ROOT = Path(__file__).resolve().parents[1]
RECIPE = ROOT / "dependencies/xkbcommon.json"
BUILDER = ROOT / "dependencies/xkbcommon/Dockerfile"
ARCHIVE_NAME = "xkbcommon-x64glibc.tar"


def verify_source(path, source):
    if (path.is_symlink() or path.stat().st_size != source["size"]
            or sha256(path) != source["sha256"]):
        raise ValueError("xkbcommon source differs from the reviewed recipe")


def fetch_source(source, cache):
    """Admit a bounded source download by its reviewed digest, including cache hits."""
    cache.mkdir(parents=True, exist_ok=True)
    destination = cache / (source["sha256"] + ".tar.gz")
    if not destination.exists():
        with tempfile.NamedTemporaryFile(dir=cache, delete=False) as pending:
            path = Path(pending.name)
        try:
            with urlopen(source["url"], timeout=60) as response, path.open("wb") as output:
                remaining = source["size"]
                while remaining:
                    data = response.read(min(remaining, 1024 * 1024))
                    if not data:
                        raise ValueError("truncated xkbcommon source download")
                    output.write(data)
                    remaining -= len(data)
                if response.read(1):
                    raise ValueError("xkbcommon source exceeds its reviewed size")
            verify_source(path, source)
            try:
                os.link(path, destination)
            except FileExistsError:
                pass
        finally:
            path.unlink(missing_ok=True)
    verify_source(destination, source)
    return destination


def check_candidate(archive, source, output, compiler):
    """Execute a keyboard-map probe against the extracted candidate library.

    This runs in the producer before attestation. Archive bytes are generated by
    this build, and the normal consumer inventory verifier checks extraction.
    The probe's headers come from the same verified upstream source archive.
    """
    candidate = Path("/tmp/candidate")
    unpack_verified(archive, {"name": "xkbcommon", "target": "x64glibc"}, candidate)
    library_dir = candidate / "targets/x64glibc"
    # Only the probe's private runtime search tree needs a SONAME symlink. The
    # distributable archive contains regular files and has no filesystem links.
    for name in ("libxkbcommon", "libxkbcommon-x11"):
        (library_dir / (name + ".so.0")).symlink_to(name + ".so")
    executable = output / "xkbcommon-probe"
    subprocess.run([
        *compiler, "-I" + str(source / "include"),
        str(ROOT / "test/dependencies/xkbcommon.c"),
        str(library_dir / "libxkbcommon.so"), str(library_dir / "libxkbcommon-x11.so"),
        "-Wl,-rpath," + str(library_dir), "-o", str(executable),
    ], check=True, timeout=60)
    environment = os.environ.copy()
    environment.pop("LD_LIBRARY_PATH", None)
    environment.pop("LD_PRELOAD", None)
    subprocess.run([str(executable)], check=True, env=environment, timeout=15)


def inside_builder(source_archive, output, image_id):
    """Compile with networking disabled inside the immutable builder image."""
    recipe_bytes = RECIPE.read_bytes()
    recipe = json.loads(recipe_bytes)
    zig = "/opt/zig/zig"
    version = subprocess.check_output([zig, "version"], text=True).strip()
    if version != recipe["zig_version"]:
        raise ValueError("xkbcommon producer requires the recipe's exact Zig version")
    compiler = [zig, *recipe["cc_args"]]
    verify_source(source_archive, recipe["source"])
    source_root = Path("/tmp/source")
    with tarfile.open(source_archive) as packed:
        packed.extractall(source_root, filter="data")
    source = source_root / recipe["source"]["directory"]
    build = Path("/tmp/build")
    meson = ["python3", "-m", "mesonbuild.mesonmain"]
    meson_version = subprocess.check_output([*meson, "--version"], text=True).strip()
    if meson_version != recipe["meson_version"]:
        raise ValueError("xkbcommon producer requires the recipe's exact Meson version")
    subprocess.run([*meson, "setup", str(build), str(source),
                    "--native-file=" + str(ROOT / "dependencies/xkbcommon/zig.ini"),
                    *recipe["meson_options"]], check=True, timeout=120)
    libraries = ("libxkbcommon", "libxkbcommon-x11")
    sonames = [name + ".so.0.13.2" for name in libraries]
    subprocess.run(["ninja", "-C", str(build), "-j2", *sonames], check=True, timeout=900)
    installed = Path("/tmp/installed")
    subprocess.run([*meson, "install", "-C", str(build), "--no-rebuild",
                    "--destdir", str(installed)], check=True, timeout=60)
    files = {"targets/x64glibc/" + name + ".so":
             (installed / "usr/lib" / soname).read_bytes()
             for name, soname in zip(libraries, sonames)}
    files["licenses/xkbcommon/LICENSE"] = (source / "LICENSE").read_bytes()
    metadata = {
        "schema_version": 1, "name": recipe["name"], "version": recipe["version"],
        "target": recipe["target"], "source": recipe["source"],
        "build": {
            "builder_image": image_id,
            "builder_recipe_sha256": sha256(BUILDER),
            "toolchain_sha256": sha256(ROOT / "dependencies/xkbcommon/zig.ini"),
            "compiler_adapter_sha256": sha256(ROOT / "dependencies/xkbcommon/cc.sh"),
            "recipe_sha256": digest(recipe_bytes),
            "producer_sha256": sha256(Path(__file__)),
            "archive_writer_sha256": sha256(Path(dependency_archive.__file__)),
            "probe_sha256": sha256(ROOT / "test/dependencies/xkbcommon.c"),
            "zig_version": version,
            "cc_args": recipe["cc_args"],
            "meson_options": recipe["meson_options"],
            "compiler": subprocess.check_output([*compiler, "--version"], text=True).splitlines()[0],
            "meson": meson_version,
            "packages": subprocess.check_output([
                "dpkg-query", "-W", "-f=${Package}\t${Version}\t${Architecture}\n",
            ], text=True).splitlines(),
        },
    }
    # Keep the candidate private until its exact bytes pass the native probe.
    archive = write_archive(build / ARCHIVE_NAME, metadata, files)
    check_candidate(archive, source, build, compiler)
    shutil.copyfile(archive, output / ARCHIVE_NAME)


def build(output, cache):
    if platform.system() != "Linux" or platform.machine() != "x86_64":
        raise ValueError("xkbcommon production requires native Linux x86_64 and Docker")
    destination = output / ARCHIVE_NAME
    if destination.exists():
        raise ValueError("xkbcommon candidate already exists; retain or inspect its original bytes")
    recipe = json.loads(RECIPE.read_bytes())
    source = fetch_source(recipe["source"], cache)
    tag = "roc-gui-xkbcommon-builder:" + sha256(BUILDER)[:24]
    subprocess.run(["docker", "build", "--platform=linux/amd64", "--tag", tag, str(BUILDER.parent)],
                   check=True, timeout=1800)
    image_id = subprocess.check_output([
        "docker", "image", "inspect", "--format", "{{.Id}}", tag,
    ], text=True).strip()
    output.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=output, prefix=".xkbcommon-") as temporary:
        stage = Path(temporary)
        subprocess.run([
            "docker", "run", "--platform=linux/amd64", "--rm", "--network=none", "--read-only",
            "--cap-drop=ALL", "--security-opt=no-new-privileges",
            "--user", f"{os.getuid()}:{os.getgid()}",
            "--tmpfs", "/tmp:exec,mode=1777", "--env", "PYTHONDONTWRITEBYTECODE=1",
            "--env", "ZIG_GLOBAL_CACHE_DIR=/tmp/zig-global",
            "--env", "ZIG_LOCAL_CACHE_DIR=/tmp/zig-local",
            "--volume", str(ROOT / "scripts") + ":/repo/scripts:ro",
            "--volume", str(ROOT / "dependencies") + ":/repo/dependencies:ro",
            "--volume", str(ROOT / "test/dependencies") + ":/repo/test/dependencies:ro",
            "--volume", str(source) + ":/source.tar.gz:ro",
            "--volume", str(stage) + ":/output",
            image_id, "python3", "/repo/scripts/build_xkbcommon.py", "--inside",
            "--image-id", image_id, "--output", "/output",
        ], check=True, timeout=1200)
        os.link(stage / ARCHIVE_NAME, destination)
    print(f"{sha256(destination)}  {destination.name}")
    return destination


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--cache", type=Path, default=Path.home() / ".cache/roc-gui/sources")
    parser.add_argument("--inside", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument("--image-id", help=argparse.SUPPRESS)
    args = parser.parse_args()
    if args.inside:
        inside_builder(Path("/source.tar.gz"), args.output, args.image_id)
    else:
        build(args.output.resolve(), args.cache.resolve())
