"""Write deterministic dependency archives without replacing published candidates."""

import hashlib
import io
import json
import os
from pathlib import Path
import tarfile
import tempfile


def digest(data):
    return hashlib.sha256(data).hexdigest()


def write_archive(output, metadata, files):
    if "dependency.json" in files or "files" in metadata:
        raise ValueError("dependency manifest and inventory are generated by the archive writer")
    manifest = dict(metadata, files={name: {"sha256": digest(data), "size": len(data)}
                                    for name, data in sorted(files.items())})
    payload = dict(files, **{"dependency.json": (json.dumps(manifest, indent=2) + "\n").encode()})
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=output.parent, delete=False) as pending:
        path = Path(pending.name)
    try:
        with tarfile.open(path, "w", format=tarfile.USTAR_FORMAT) as packed:
            for name, data in sorted(payload.items()):
                entry = tarfile.TarInfo(name)
                entry.size = len(data)
                entry.mode = 0o644
                packed.addfile(entry, io.BytesIO(data))
        os.link(path, output)
    finally:
        path.unlink(missing_ok=True)
    return output
