(test "sample pause inspect filter and resume"
  (steps
    (expect-system-samplers 0)
    (click (role button :name "Resume sampling"))
    (expect-system-samplers 1)
    (await-ticks 2)
    (expect-system-samples 2)
    (expect-visible (text "CPU: 42.7%"))
    (expect-visible (text "Processes: 24"))
    (click (role button :name "Inspect process service-0000"))
    (expect-visible (text "Selected process 1000"))
    (replace-text (role textbox :name "Filter processes") "service-0023")
    (expect-count (button-prefix "Inspect process service-") 1)
    (click (role button :name "Sort processes by memory"))
    (click (role button :name "Pause sampling"))
    (expect-subscriptions 0)
    (expect-system-samplers 0)
    (await-task)
    (expect-visible (text "Paused"))))
