(test "pause and resume bounded sampling"
  (steps
    (expect-visible (text "CPU: unavailable"))
    (expect-subscriptions 0)
    (click (role button :name "Resume sampling"))
    (expect-subscriptions 1)
    (await-ticks 3)
    (expect-visible (text-prefix "Sample 3:"))
    (click (role button :name "Pause sampling"))
    (expect-subscriptions 0)
    (await-task)
    (expect-visible (text "Paused"))
    (click (role button :name "Resume sampling"))
    (await-ticks 2)
    (expect-visible (text-prefix "Sample 5:"))))
