(test "clipboard history scales through ordinary clipboard changes"
  (benchmark :warmups 0 :samples 1 :iterations 1 :scale 100 :initial-size 0 :change-size 100)
  (steps
    (click (role button :name "Start clipboard capture"))
    (clipboard-text "ordinary item 001")
    (await-ticks 1)
    (clipboard-text "ordinary item 002")
    (await-ticks 1)
    (clipboard-text "ordinary item 003")
    (await-ticks 1)
    (clipboard-text "ordinary item 004")
    (await-ticks 1)
    (clipboard-text "ordinary item 005")
    (await-ticks 1)
    (clipboard-text "ordinary item 006")
    (await-ticks 1)
    (clipboard-text "ordinary item 007")
    (await-ticks 1)
    (clipboard-text "ordinary item 008")
    (await-ticks 1)
    (clipboard-text "ordinary item 009")
    (await-ticks 1)
    (clipboard-text "ordinary item 010")
    (await-ticks 1)
    (clipboard-text "ordinary item 011")
    (await-ticks 1)
    (clipboard-text "ordinary item 012")
    (await-ticks 1)
    (clipboard-text "ordinary item 013")
    (await-ticks 1)
    (clipboard-text "ordinary item 014")
    (await-ticks 1)
    (clipboard-text "ordinary item 015")
    (await-ticks 1)
    (clipboard-text "ordinary item 016")
    (await-ticks 1)
    (clipboard-text "ordinary item 017")
    (await-ticks 1)
    (clipboard-text "ordinary item 018")
    (await-ticks 1)
    (clipboard-text "ordinary item 019")
    (await-ticks 1)
    (clipboard-text "ordinary item 020")
    (await-ticks 1)
    (clipboard-text "ordinary item 021")
    (await-ticks 1)
    (clipboard-text "ordinary item 022")
    (await-ticks 1)
    (clipboard-text "ordinary item 023")
    (await-ticks 1)
    (clipboard-text "ordinary item 024")
    (await-ticks 1)
    (clipboard-text "ordinary item 025")
    (await-ticks 1)
    (clipboard-text "ordinary item 026")
    (await-ticks 1)
    (clipboard-text "ordinary item 027")
    (await-ticks 1)
    (clipboard-text "ordinary item 028")
    (await-ticks 1)
    (clipboard-text "ordinary item 029")
    (await-ticks 1)
    (clipboard-text "ordinary item 030")
    (await-ticks 1)
    (clipboard-text "ordinary item 031")
    (await-ticks 1)
    (clipboard-text "ordinary item 032")
    (await-ticks 1)
    (clipboard-text "ordinary item 033")
    (await-ticks 1)
    (clipboard-text "ordinary item 034")
    (await-ticks 1)
    (clipboard-text "ordinary item 035")
    (await-ticks 1)
    (clipboard-text "ordinary item 036")
    (await-ticks 1)
    (clipboard-text "ordinary item 037")
    (await-ticks 1)
    (clipboard-text "ordinary item 038")
    (await-ticks 1)
    (clipboard-text "ordinary item 039")
    (await-ticks 1)
    (clipboard-text "ordinary item 040")
    (await-ticks 1)
    (clipboard-text "ordinary item 041")
    (await-ticks 1)
    (clipboard-text "ordinary item 042")
    (await-ticks 1)
    (clipboard-text "ordinary item 043")
    (await-ticks 1)
    (clipboard-text "ordinary item 044")
    (await-ticks 1)
    (clipboard-text "ordinary item 045")
    (await-ticks 1)
    (clipboard-text "ordinary item 046")
    (await-ticks 1)
    (clipboard-text "ordinary item 047")
    (await-ticks 1)
    (clipboard-text "ordinary item 048")
    (await-ticks 1)
    (clipboard-text "ordinary item 049")
    (await-ticks 1)
    (clipboard-text "ordinary item 050")
    (await-ticks 1)
    (clipboard-text "ordinary item 051")
    (await-ticks 1)
    (clipboard-text "ordinary item 052")
    (await-ticks 1)
    (clipboard-text "ordinary item 053")
    (await-ticks 1)
    (clipboard-text "ordinary item 054")
    (await-ticks 1)
    (clipboard-text "ordinary item 055")
    (await-ticks 1)
    (clipboard-text "ordinary item 056")
    (await-ticks 1)
    (clipboard-text "ordinary item 057")
    (await-ticks 1)
    (clipboard-text "ordinary item 058")
    (await-ticks 1)
    (clipboard-text "ordinary item 059")
    (await-ticks 1)
    (clipboard-text "ordinary item 060")
    (await-ticks 1)
    (clipboard-text "ordinary item 061")
    (await-ticks 1)
    (clipboard-text "ordinary item 062")
    (await-ticks 1)
    (clipboard-text "ordinary item 063")
    (await-ticks 1)
    (clipboard-text "ordinary item 064")
    (await-ticks 1)
    (clipboard-text "ordinary item 065")
    (await-ticks 1)
    (clipboard-text "ordinary item 066")
    (await-ticks 1)
    (clipboard-text "ordinary item 067")
    (await-ticks 1)
    (clipboard-text "ordinary item 068")
    (await-ticks 1)
    (clipboard-text "ordinary item 069")
    (await-ticks 1)
    (clipboard-text "ordinary item 070")
    (await-ticks 1)
    (clipboard-text "ordinary item 071")
    (await-ticks 1)
    (clipboard-text "ordinary item 072")
    (await-ticks 1)
    (clipboard-text "ordinary item 073")
    (await-ticks 1)
    (clipboard-text "ordinary item 074")
    (await-ticks 1)
    (clipboard-text "ordinary item 075")
    (await-ticks 1)
    (clipboard-text "ordinary item 076")
    (await-ticks 1)
    (clipboard-text "ordinary item 077")
    (await-ticks 1)
    (clipboard-text "ordinary item 078")
    (await-ticks 1)
    (clipboard-text "ordinary item 079")
    (await-ticks 1)
    (clipboard-text "ordinary item 080")
    (await-ticks 1)
    (clipboard-text "ordinary item 081")
    (await-ticks 1)
    (clipboard-text "ordinary item 082")
    (await-ticks 1)
    (clipboard-text "ordinary item 083")
    (await-ticks 1)
    (clipboard-text "ordinary item 084")
    (await-ticks 1)
    (clipboard-text "ordinary item 085")
    (await-ticks 1)
    (clipboard-text "ordinary item 086")
    (await-ticks 1)
    (clipboard-text "ordinary item 087")
    (await-ticks 1)
    (clipboard-text "ordinary item 088")
    (await-ticks 1)
    (clipboard-text "ordinary item 089")
    (await-ticks 1)
    (clipboard-text "ordinary item 090")
    (await-ticks 1)
    (clipboard-text "ordinary item 091")
    (await-ticks 1)
    (clipboard-text "ordinary item 092")
    (await-ticks 1)
    (clipboard-text "ordinary item 093")
    (await-ticks 1)
    (clipboard-text "ordinary item 094")
    (await-ticks 1)
    (clipboard-text "ordinary item 095")
    (await-ticks 1)
    (clipboard-text "ordinary item 096")
    (await-ticks 1)
    (clipboard-text "ordinary item 097")
    (await-ticks 1)
    (clipboard-text "ordinary item 098")
    (await-ticks 1)
    (clipboard-text "ordinary item 099")
    (await-ticks 1)
    (clipboard-text "ordinary item 100")
    (await-ticks 1)
    (mark-metrics)
    (expect-count (text-prefix "ordinary item ") 100)))
