(test "keyframe, scrub, and bounded playback"
  (steps
    (click (role button :name "Add keyframe"))
    (expect-visible (text "Keyframes in document: 1"))
    (expect-visible (role canvas-item :name "Keyframe 0"))
    (click (role button :name "Scrub backward"))
    (expect-visible (text "Already at the first frame"))
    (click (role button :name "Scrub forward"))
    (expect-visible (text "Frame 10 of 120"))
    (drag (role canvas :name "Timeline track") 580 40 580 40)
    (expect-visible (text "Scrubbed to frame 60"))
    (click (role button :name "Play"))
    (expect-subscriptions 1)
    (await-ticks 2)
    (expect-visible (text "Frame 62 of 120"))
    (click (role button :name "Pause"))
    (expect-subscriptions 0)
    (expect-visible (text "Paused at Frame 62 of 120"))))
