(test "keyframes and the playhead are drawn on the timeline track"
  (steps
    (settle)
    (click (role button :name "Add keyframe"))
    (click (role button :name "Scrub forward"))
    (click (role button :name "Scrub forward"))
    (click (role button :name "Scrub forward"))
    (click (role button :name "Add keyframe"))
    (click (role button :name "Scrub forward"))
    (click (role button :name "Scrub forward"))
    (click (role button :name "Scrub forward"))
    (click (role button :name "Scrub forward"))
    (click (role button :name "Add keyframe"))
    (settle)
    (expect-visible (text "Frame 70 of 120"))
    (expect-visible (role canvas-item :name "Keyframe 70"))
    (screenshot "timeline-keyframes" :region (role panel :name "Timeline") :pad 8)
    (click (role button :name "Play"))
    (await-task)
    (settle)
    (screenshot "timeline-playing" :region (role panel :name "Timeline") :pad 8)
    (click (role button :name "Pause"))
    (settle)
    (screenshot "window-paused")))
