(test "a long layer list scrolls and never displaces the timeline or status bar"
  (steps
    (settle)
    (click (role button :name "Add rectangle"))
    (click (role button :name "Add ellipse"))
    (click (role button :name "Add rectangle"))
    (click (role button :name "Add ellipse"))
    (click (role button :name "Add rectangle"))
    (click (role button :name "Add ellipse"))
    (click (role button :name "Add rectangle"))
    (click (role button :name "Add ellipse"))
    (click (role button :name "Add rectangle"))
    (click (role button :name "Add ellipse"))
    (click (role button :name "Add rectangle"))
    (click (role button :name "Add ellipse"))
    (click (role button :name "Add rectangle"))
    (click (role button :name "Add ellipse"))
    (click (role button :name "Add rectangle"))
    (click (role button :name "Add ellipse"))
    (click (role button :name "Add rectangle"))
    (click (role button :name "Add ellipse"))
    (click (role button :name "Add rectangle"))
    (click (role button :name "Add ellipse"))
    (click (role button :name "Add rectangle"))
    (click (role button :name "Add ellipse"))
    (settle)
    (expect-visible (text "LAYERS (24)"))
    (expect-on-screen (role canvas :name "Timeline track"))
    (expect-on-screen (role button :name "Play"))
    (expect-on-screen (role button :name "Add keyframe"))
    (expect-on-screen (role row :name "Status bar"))
    (screenshot "window-many-layers")
    (screenshot "layers-many" :region (role panel :name "Layers") :pad 8)))
