(test "scan and inspect native Redis values"
  (steps
    (expect-visible (role column :name "Redis Explorer"))
    (click (role button :name "Connect to Redis"))
    (await-task)
    (expect-tcp-streams 1)
    (click (role button :name "Refresh Redis keys"))
    (await-task)
    (expect-visible (text "Keys: 5"))
    (expect-count (button-prefix "Inspect Redis key profile:") 5)
    (click (role button :name "Inspect Redis key profile:ada"))
    (await-task)
    (expect-visible (role panel :name "Value inspector"))
    (expect-visible (text "Type: hash"))
    (expect-visible (text "Value 0: name: Ada Lovelace"))
    (expect-visible (text "no expiration"))
    (click (role button :name "Inspect Redis key profile:grace"))
    (await-task)
    (expect-visible (text "Value 0: Grace Hopper"))
    (expect-visible (text "expires in 60000 ms"))
    (click (role button :name "Inspect Redis key profile:recent"))
    (await-task)
    (expect-visible (text "Type: list"))
    (expect-visible (text "Value 1: 1: grace"))
    (click (role button :name "Inspect Redis key profile:roles"))
    (await-task)
    (expect-visible (text "Type: set"))
    (expect-visible (text "Value 0: member: admin"))
    (click (role button :name "Inspect Redis key profile:scores"))
    (await-task)
    (expect-visible (text "Type: sorted set"))
    (expect-visible (text "Value 1: grace: 99"))
    (expect-tcp-counters 1 1 17 17 0)))
