(test "a pattern that matches nothing is an ordinary empty result"
  (grants
    (tcp "127.0.0.1:36379")
    (server "fixture_server.py" 36379))
  (steps
    (click (role button :name "Connect to Redis"))
    (await-task)
    (click (role button :name "Refresh Redis keys"))
    (await-task)
    (expect-visible (text "Keys: 5"))
    (click (role button :name "Inspect Redis key profile:grace"))
    (await-task)
    (expect-visible (text "Key: profile:grace"))
    (replace-text (role textbox :name "Key pattern") "absent:*")
    (submit (role textbox :name "Key pattern"))
    (await-task)
    (expect-visible (text "Keys: 0"))
    (expect-count (button-prefix "Inspect Redis key ") 0)
    (expect-visible (text "Select a key to inspect its value"))
    (expect-not-visible (role panel :name "Redis error"))
    (replace-text (role textbox :name "Key pattern") "profile:*")
    (submit (role textbox :name "Key pattern"))
    (await-task)
    (expect-visible (text "Keys: 5"))))
