(test "a scan after an inspection error clears the error"
  (steps
    (click (role button :name "Connect to Redis"))
    (await-task)
    (replace-text (role textbox :name "Key pattern") "unsupported:*")
    (click (role button :name "Refresh Redis keys"))
    (await-task)
    (click (role button :name "Inspect Redis key unsupported:events"))
    (await-task)
    (expect-visible (role panel :name "Redis error"))
    (replace-text (role textbox :name "Key pattern") "profile:*")
    (click (role button :name "Refresh Redis keys"))
    (await-task)
    (expect-not-visible (role panel :name "Redis error"))
    (expect-visible (text "Keys: 5"))
    (click (role button :name "Inspect Redis key profile:grace"))
    (await-task)
    (expect-visible (text "Type: string"))
    (expect-visible (text "Value 0: Grace Hopper"))))
