# Use the same pinned compiler arguments for upstream CMake and archive probes.
file(READ "${CMAKE_CURRENT_LIST_DIR}/../freetype.json" recipe)
string(JSON argument_count LENGTH "${recipe}" cc_args)
math(EXPR last_argument "${argument_count} - 1")
set(compiler_arguments "")
foreach(index RANGE ${last_argument})
  string(JSON argument GET "${recipe}" cc_args ${index})
  list(APPEND compiler_arguments "${argument}")
endforeach()
list(JOIN compiler_arguments " " compiler_arguments)
find_program(CMAKE_C_COMPILER zig REQUIRED)
set(CMAKE_C_COMPILER_ARG1 "${compiler_arguments}")
set(CMAKE_SKIP_RPATH TRUE)
